-- Canonical freight-order coverage.
--
-- The freight order tables were previously present only in the application
-- schema/runtime history. Keep the bootstrap definition in 0001 for fresh
-- databases and use this additive migration for environments that already
-- recorded 0001.

CREATE TABLE IF NOT EXISTS air_freight_orders (
  id SERIAL PRIMARY KEY,
  order_number TEXT NOT NULL UNIQUE,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  portal_customer_id INTEGER REFERENCES portal_customers(id) ON DELETE SET NULL,
  customer_id INTEGER,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_phone TEXT,
  customer_email TEXT,
  customer_company TEXT,
  origin_city TEXT NOT NULL DEFAULT '',
  origin_airport TEXT NOT NULL DEFAULT '',
  destination_city TEXT NOT NULL DEFAULT '',
  destination_airport TEXT NOT NULL DEFAULT '',
  dest_airport TEXT NOT NULL DEFAULT '',
  trade_type TEXT NOT NULL DEFAULT 'export',
  service_mode TEXT NOT NULL DEFAULT 'airport_to_airport',
  service_level TEXT NOT NULL DEFAULT 'standard',
  incoterm TEXT,
  commodity TEXT,
  hs_code TEXT,
  cargo_type TEXT NOT NULL DEFAULT 'general',
  pieces INTEGER,
  koli INTEGER,
  packing_type TEXT,
  gross_weight NUMERIC(12,3),
  volumetric_weight NUMERIC(12,3),
  total_volumetric_weight NUMERIC(12,3),
  chargeable_weight NUMERIC(12,3),
  volume_cbm NUMERIC(12,3),
  dimension_rows JSONB DEFAULT '[]'::jsonb,
  pickup_date DATE,
  ready_cargo_date DATE,
  preferred_flight_date DATE,
  target_arrival_date DATE,
  etd_requested TEXT,
  additional_services TEXT[],
  selected_additional_services JSONB DEFAULT '[]'::jsonb,
  selected_estimate_option TEXT,
  special_instructions TEXT,
  notes TEXT,
  estimated_price NUMERIC(14,2),
  estimated_price_idr NUMERIC(14,2),
  currency TEXT DEFAULT 'IDR',
  pricing_breakdown JSONB,
  selected_rate_id INTEGER,
  candidate_rate_ids JSONB DEFAULT '[]'::jsonb,
  selected_rfq_submission_id INTEGER,
  final_rate_id INTEGER,
  final_price NUMERIC(14,2),
  final_price_idr NUMERIC(14,2),
  final_rate_per_kg NUMERIC(12,2),
  fuel_surcharge NUMERIC(12,2),
  security_surcharge NUMERIC(12,2),
  awb_fee NUMERIC(12,2),
  handling_fee NUMERIC(12,2),
  xray_fee NUMERIC(12,2),
  doc_fee NUMERIC(12,2),
  customs_clearance_fee NUMERIC(12,2),
  pickup_trucking NUMERIC(12,2),
  delivery_trucking NUMERIC(12,2),
  cargo_surcharge NUMERIC(12,2),
  markup_amount NUMERIC(12,2),
  ppn_pct NUMERIC(5,2) DEFAULT 11,
  ppn_amount NUMERIC(14,2),
  subtotal NUMERIC(14,2) DEFAULT 0,
  grand_total NUMERIC(14,2) DEFAULT 0,
  final_breakdown JSONB,
  admin_notes TEXT,
  airline TEXT,
  flight_number TEXT,
  etd TEXT,
  eta TEXT,
  transit_days INTEGER,
  awb_number TEXT,
  tracking_notes TEXT,
  status TEXT NOT NULL DEFAULT 'inquiry',
  price_status TEXT NOT NULL DEFAULT 'estimate',
  source TEXT NOT NULL DEFAULT 'customer_portal',
  approval_token TEXT UNIQUE,
  approval_token_expires_at TIMESTAMPTZ,
  booking_number TEXT,
  mawb TEXT,
  hawb TEXT,
  decline_reason TEXT,
  declined_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  admin_quote_attachment_url TEXT,
  quote_token TEXT UNIQUE,
  quote_sent_at TIMESTAMPTZ,
  booking_confirmed_at TIMESTAMPTZ,
  booking_attachment_url TEXT,
  approved_vendor_id INTEGER REFERENCES suppliers(id) ON DELETE SET NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ocean_freight_orders (
  id SERIAL PRIMARY KEY,
  order_number TEXT NOT NULL UNIQUE,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  portal_customer_id INTEGER REFERENCES portal_customers(id) ON DELETE SET NULL,
  customer_id INTEGER,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_phone TEXT,
  customer_email TEXT,
  customer_company TEXT,
  origin_city TEXT NOT NULL DEFAULT '',
  origin_port TEXT NOT NULL DEFAULT '',
  destination_city TEXT NOT NULL DEFAULT '',
  destination_port TEXT NOT NULL DEFAULT '',
  trade_type TEXT NOT NULL DEFAULT 'export',
  service_mode TEXT NOT NULL DEFAULT 'port_to_port',
  shipment_type TEXT NOT NULL DEFAULT 'FCL',
  container_type TEXT,
  container_qty INTEGER,
  total_cbm NUMERIC(12,3),
  gross_weight NUMERIC(12,3),
  koli INTEGER,
  commodity TEXT NOT NULL DEFAULT 'General Cargo',
  hs_code TEXT,
  cargo_value NUMERIC(14,2),
  cargo_condition TEXT NOT NULL DEFAULT 'general',
  incoterm TEXT,
  etd_preferred TEXT,
  eta_target TEXT,
  selected_additional_services JSONB DEFAULT '[]'::jsonb,
  selected_estimate_option TEXT,
  estimated_price NUMERIC(14,2),
  estimated_price_idr NUMERIC(14,2),
  currency TEXT DEFAULT 'IDR',
  pricing_breakdown JSONB,
  selected_rate_id INTEGER,
  candidate_rate_ids JSONB DEFAULT '[]'::jsonb,
  final_rate_id INTEGER,
  final_price NUMERIC(14,2),
  final_price_idr NUMERIC(14,2),
  markup_amount NUMERIC(14,2),
  ppn_pct NUMERIC(5,2) DEFAULT 11,
  ppn_amount NUMERIC(14,2),
  grand_total NUMERIC(14,2),
  final_breakdown JSONB,
  admin_notes TEXT,
  customer_notes TEXT,
  price_status TEXT NOT NULL DEFAULT 'estimate',
  status TEXT NOT NULL DEFAULT 'waiting_rate',
  source TEXT NOT NULL DEFAULT 'customer_portal',
  booking_number TEXT,
  carrier TEXT,
  vessel_name TEXT,
  voyage TEXT,
  etd TEXT,
  eta TEXT,
  pol TEXT,
  pod TEXT,
  container_number TEXT,
  seal_number TEXT,
  bl_number TEXT,
  booking_confirmation_url TEXT,
  admin_quote_attachment_url TEXT,
  quote_token TEXT UNIQUE,
  quote_sent_at TIMESTAMPTZ,
  booking_confirmed_at TIMESTAMPTZ,
  tracking_status TEXT,
  tracking_notes TEXT,
  tracking_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE air_freight_orders
    ADD COLUMN IF NOT EXISTS customer_id INTEGER,
    ADD COLUMN IF NOT EXISTS portal_customer_id INTEGER,
    ADD COLUMN IF NOT EXISTS customer_company TEXT,
    ADD COLUMN IF NOT EXISTS origin_city TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS destination_city TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS destination_airport TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_mode TEXT DEFAULT 'airport_to_airport',
    ADD COLUMN IF NOT EXISTS service_level TEXT DEFAULT 'standard',
    ADD COLUMN IF NOT EXISTS incoterm TEXT,
    ADD COLUMN IF NOT EXISTS hs_code TEXT,
    ADD COLUMN IF NOT EXISTS koli INTEGER,
    ADD COLUMN IF NOT EXISTS total_volumetric_weight NUMERIC(12,3),
    ADD COLUMN IF NOT EXISTS dimension_rows JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS pickup_date DATE,
    ADD COLUMN IF NOT EXISTS ready_cargo_date DATE,
    ADD COLUMN IF NOT EXISTS preferred_flight_date DATE,
    ADD COLUMN IF NOT EXISTS target_arrival_date DATE,
    ADD COLUMN IF NOT EXISTS selected_additional_services JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS selected_estimate_option TEXT,
    ADD COLUMN IF NOT EXISTS estimated_price_idr NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'IDR',
    ADD COLUMN IF NOT EXISTS pricing_breakdown JSONB,
    ADD COLUMN IF NOT EXISTS selected_rate_id INTEGER,
    ADD COLUMN IF NOT EXISTS candidate_rate_ids JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS final_rate_id INTEGER,
    ADD COLUMN IF NOT EXISTS final_price NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS final_price_idr NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS final_breakdown JSONB,
    ADD COLUMN IF NOT EXISTS admin_notes TEXT,
    ADD COLUMN IF NOT EXISTS price_status TEXT DEFAULT 'estimate',
    ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'customer_portal',
    ADD COLUMN IF NOT EXISTS approval_token TEXT,
    ADD COLUMN IF NOT EXISTS approval_token_expires_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS booking_number TEXT,
    ADD COLUMN IF NOT EXISTS mawb TEXT,
    ADD COLUMN IF NOT EXISTS hawb TEXT,
    ADD COLUMN IF NOT EXISTS decline_reason TEXT,
    ADD COLUMN IF NOT EXISTS declined_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS booking_attachment_url TEXT,
    ADD COLUMN IF NOT EXISTS created_by TEXT;
  CREATE UNIQUE INDEX IF NOT EXISTS air_freight_orders_approval_token_uidx
    ON air_freight_orders (approval_token) WHERE approval_token IS NOT NULL;
EXCEPTION WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ocean_freight_orders
    ADD COLUMN IF NOT EXISTS portal_customer_id INTEGER,
    ADD COLUMN IF NOT EXISTS customer_company TEXT,
    ADD COLUMN IF NOT EXISTS ppn_pct NUMERIC(5,2) DEFAULT 11,
    ADD COLUMN IF NOT EXISTS tracking_notes TEXT,
    ADD COLUMN IF NOT EXISTS tracking_updated_at TIMESTAMPTZ;
EXCEPTION WHEN undefined_table THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS air_freight_orders_company_status_idx
  ON air_freight_orders (company_id, status);
CREATE INDEX IF NOT EXISTS air_freight_orders_portal_customer_idx
  ON air_freight_orders (portal_customer_id);
CREATE INDEX IF NOT EXISTS ocean_freight_orders_company_status_idx
  ON ocean_freight_orders (company_id, status);
CREATE INDEX IF NOT EXISTS ocean_freight_orders_portal_customer_idx
  ON ocean_freight_orders (portal_customer_id);

CREATE TABLE IF NOT EXISTS air_freight_tracking_events (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES air_freight_orders(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  note TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);