#!/usr/bin/env python3
"""
Insert the 48 missing translation keys (services.* × 14 + oceanFreight.* × 34)
into 16 locale files.

Insertion anchors (same structure across all locales):
  - services section:    after `    tryOther: '...',`  → before closing `  },`
  - oceanFreight section: after `    ctaWa: '...',`    → before closing `  },`

Rules:
  - values-only insertion; no key rename, no namespace move, no empty values
  - preserve single-quote style used by each locale file
  - placeholder strings (LCL Cargo, HS Code, CBM) kept as-is per language norms
"""
import re, sys, os

LOCALES_DIR = os.path.join(os.path.dirname(__file__), '..', 'src', 'i18n', 'locales')

# ── Translation table ────────────────────────────────────────────────────────
# Each locale gets: { key: value } for both services and oceanFreight additions.

TRANSLATIONS = {
    # ── Arabic UAE ────────────────────────────────────────────────────────────
    'ar-AE': {
        'svc': dict(
            back='رجوع',
            serviceUnit='خدمة',
            realtimeUpdated='محدَّث',
            realtimeLive='مباشر',
            truckingBannerTitle='احجز أسطول الشاحنات مباشرةً',
            truckingBannerDesc='اختر من بين 12 نوعاً من الأساطيل، تحقق من تكلفة الشحن فوراً، وأضف الخدمات حسب حاجتك. سهل وشفاف.',
            truckingBannerCta='تحقق من التكلفة واحجز',
            folderViewContents='عرض المحتويات',
            folderMore='المزيد',
            truckingBannerBadge='حجز الشاحنات',
            folderCardDesc='خدمات النقل البري وتأجير الحاويات للتسليم المحلي وبين المدن.',
            folderViewAll='عرض جميع الخدمات',
            sellingPrice='سعر البيع',
            dialogSub='اختر الخدمة التي تناسب احتياجاتك',
        ),
        'of': dict(
            successDesc='تم إرسال طلب عرض أسعار الشحن البحري. سيرسل فريقنا السعر النهائي بعد تأكيد شركة الشحن / الشريك.',
            backToHome='العودة إلى الرئيسية',
            yourData='بياناتك',
            customerNameLabel='الاسم',
            customerNamePlaceholder='الاسم الكامل',
            customerPhoneLabel='رقم الهاتف / واتساب',
            customerCompanyLabel='الشركة',
            customerNotesLabel='ملاحظات إضافية',
            customerNotesPlaceholder='تعليمات خاصة...',
            goBack='رجوع',
            sending='جاري الإرسال...',
            koliQty='عدد الطرود',
            containerFinalNote='التفاصيل النهائية وفقاً لتأكيد الناقل.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='السعر بناءً على CBM المشغول',
            checkEstimate='احسب التقدير',
            calculating='جاري الحساب...',
            estimateResults='نتائج التقدير',
            recalculate='إعادة الحساب',
            noRate='لا يوجد سعر متاح لهذا المسار',
            noRateHint='يرجى تقديم استفسار للحصول على عرض سعر يدوي من فريقنا.',
            requestManual='طلب عرض سعر يدوي',
            initialEstimate='التقدير الأولي',
            dayUnit='يوم',
            validUntil='صالح حتى',
            selectEstimate='اختر هذا التقدير',
            estimateNoticeShort='هذا تقدير أولي. السعر النهائي يُؤكَّد بعد حصول الإدارة/المورد على تأكيد من شركة الشحن/الشريك.',
            estimateNoticeFull='هذا تقدير أولي. السعر النهائي يُؤكَّد بعد حصول الإدارة/المورد على تأكيد من شركة الشحن، NVOCC، co-loader، أو الشريك.',
            breakdownTitle='تفاصيل التقدير',
            totalBreakdown='إجمالي التقدير',
            custNameRequired='اسم العميل مطلوب',
            hsCodeOptional='HS Code (اختياري)',
            requestFinalQuote='طلب عرض السعر النهائي',
        ),
    },
    # ── Arabic SA ─────────────────────────────────────────────────────────────
    'ar-SA': {
        'svc': dict(
            back='رجوع',
            serviceUnit='خدمة',
            realtimeUpdated='محدَّث',
            realtimeLive='مباشر',
            truckingBannerTitle='احجز أسطول الشاحنات مباشرةً',
            truckingBannerDesc='اختر من بين 12 نوعاً من الأساطيل، تحقق من تكلفة الشحن فوراً، وأضف الخدمات حسب حاجتك. سهل وشفاف.',
            truckingBannerCta='تحقق من التكلفة واحجز',
            folderViewContents='عرض المحتويات',
            folderMore='المزيد',
            truckingBannerBadge='حجز الشاحنات',
            folderCardDesc='خدمات النقل البري وتأجير الحاويات للتسليم المحلي وبين المدن.',
            folderViewAll='عرض جميع الخدمات',
            sellingPrice='سعر البيع',
            dialogSub='اختر الخدمة التي تناسب احتياجاتك',
        ),
        'of': dict(
            successDesc='تم إرسال طلب عرض أسعار الشحن البحري. سيرسل فريقنا السعر النهائي بعد تأكيد شركة الشحن / الشريك.',
            backToHome='العودة إلى الرئيسية',
            yourData='بياناتك',
            customerNameLabel='الاسم',
            customerNamePlaceholder='الاسم الكامل',
            customerPhoneLabel='رقم الهاتف / واتساب',
            customerCompanyLabel='الشركة',
            customerNotesLabel='ملاحظات إضافية',
            customerNotesPlaceholder='تعليمات خاصة...',
            goBack='رجوع',
            sending='جاري الإرسال...',
            koliQty='عدد الطرود',
            containerFinalNote='التفاصيل النهائية وفقاً لتأكيد الناقل.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='السعر بناءً على CBM المشغول',
            checkEstimate='احسب التقدير',
            calculating='جاري الحساب...',
            estimateResults='نتائج التقدير',
            recalculate='إعادة الحساب',
            noRate='لا يوجد سعر متاح لهذا المسار',
            noRateHint='يرجى تقديم استفسار للحصول على عرض سعر يدوي من فريقنا.',
            requestManual='طلب عرض سعر يدوي',
            initialEstimate='التقدير الأولي',
            dayUnit='يوم',
            validUntil='صالح حتى',
            selectEstimate='اختر هذا التقدير',
            estimateNoticeShort='هذا تقدير أولي. السعر النهائي يُؤكَّد بعد حصول الإدارة/المورد على تأكيد من شركة الشحن/الشريك.',
            estimateNoticeFull='هذا تقدير أولي. السعر النهائي يُؤكَّد بعد حصول الإدارة/المورد على تأكيد من شركة الشحن، NVOCC، co-loader، أو الشريك.',
            breakdownTitle='تفاصيل التقدير',
            totalBreakdown='إجمالي التقدير',
            custNameRequired='اسم العميل مطلوب',
            hsCodeOptional='HS Code (اختياري)',
            requestFinalQuote='طلب عرض السعر النهائي',
        ),
    },
    # ── German ────────────────────────────────────────────────────────────────
    'de-DE': {
        'svc': dict(
            back='Zurück',
            serviceUnit='Dienst',
            realtimeUpdated='Aktualisiert',
            realtimeLive='Live',
            truckingBannerTitle='Trucking-Flotte direkt buchen',
            truckingBannerDesc='Wählen Sie aus 12 Flottentypen, prüfen Sie sofort die Frachtkosten und fügen Sie Dienste nach Bedarf hinzu. Einfach und transparent.',
            truckingBannerCta='Kosten prüfen & buchen',
            folderViewContents='Inhalt anzeigen',
            folderMore='weitere',
            truckingBannerBadge='Trucking-Buchung',
            folderCardDesc='Landtransport- und Containermiete für lokale und städteübergreifende Lieferbedürfnisse.',
            folderViewAll='Alle Dienste anzeigen',
            sellingPrice='Verkaufspreis',
            dialogSub='Wählen Sie den Dienst, der Ihren Anforderungen entspricht',
        ),
        'of': dict(
            successDesc='Ihre Ocean-Freight-Anfrage wurde gesendet. Unser Team sendet den endgültigen Preis nach Bestätigung durch die Reederei / den Partner.',
            backToHome='Zurück zur Startseite',
            yourData='Ihre Daten',
            customerNameLabel='Name',
            customerNamePlaceholder='Vollständiger Name',
            customerPhoneLabel='Telefon / WhatsApp',
            customerCompanyLabel='Unternehmen',
            customerNotesLabel='Zusätzliche Hinweise',
            customerNotesPlaceholder='Besondere Anweisungen...',
            goBack='Zurück',
            sending='Wird gesendet...',
            koliQty='Anzahl der Pakete',
            containerFinalNote='Endgültige Details gemäß Bestätigung des Spediteurs.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Preis basiert auf belegtem CBM',
            checkEstimate='Schätzung berechnen',
            calculating='Wird berechnet...',
            estimateResults='Schätzergebnisse',
            recalculate='Neu berechnen',
            noRate='Kein Tarif für diese Route verfügbar',
            noRateHint='Bitte reichen Sie eine Anfrage ein, um ein manuelles Angebot von unserem Team zu erhalten.',
            requestManual='Manuelles Angebot anfordern',
            initialEstimate='Erstschätzung',
            dayUnit='Tage',
            validUntil='Gültig bis',
            selectEstimate='Diese Schätzung auswählen',
            estimateNoticeShort='Dies ist eine Erstschätzung. Der Endpreis wird nach Bestätigung der Reederei/des Partners durch Admin/Anbieter bestätigt.',
            estimateNoticeFull='Dies ist eine Erstschätzung. Der Endpreis wird nach Bestätigung durch Reederei, NVOCC, Co-Loader oder Partner bestätigt.',
            breakdownTitle='Kostenaufschlüsselung',
            totalBreakdown='Gesamtschätzung',
            custNameRequired='Kundenname ist erforderlich',
            hsCodeOptional='HS Code (optional)',
            requestFinalQuote='Endangebot anfordern',
        ),
    },
    # ── Spanish ───────────────────────────────────────────────────────────────
    'es-ES': {
        'svc': dict(
            back='Volver',
            serviceUnit='servicio',
            realtimeUpdated='Actualizado',
            realtimeLive='En vivo',
            truckingBannerTitle='Reserva Flota de Camiones Directamente',
            truckingBannerDesc='Elige entre 12 tipos de flota, consulta el costo de envío al instante y agrega servicios según tu necesidad. Fácil y transparente.',
            truckingBannerCta='Ver Costo & Reservar',
            folderViewContents='Ver Contenidos',
            folderMore='más',
            truckingBannerBadge='Reserva de Camiones',
            folderCardDesc='Servicios de transporte terrestre y alquiler de contenedores para entregas locales e interurbanas.',
            folderViewAll='Ver Todos los Servicios',
            sellingPrice='Precio de Venta',
            dialogSub='Elige el servicio que se adapta a tus necesidades',
        ),
        'of': dict(
            successDesc='Tu solicitud de cotización de Ocean Freight ha sido enviada. Nuestro equipo enviará el precio final tras la confirmación de la naviera / socio.',
            backToHome='Volver al Inicio',
            yourData='Tus Datos',
            customerNameLabel='Nombre',
            customerNamePlaceholder='Nombre completo',
            customerPhoneLabel='Teléfono / WhatsApp',
            customerCompanyLabel='Empresa',
            customerNotesLabel='Notas Adicionales',
            customerNotesPlaceholder='Instrucciones especiales...',
            goBack='Volver',
            sending='Enviando...',
            koliQty='Cantidad de Bultos',
            containerFinalNote='Detalles finales según confirmación del transportista.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Tarifa basada en CBM utilizado',
            checkEstimate='Calcular Estimación',
            calculating='Calculando...',
            estimateResults='Resultados de Estimación',
            recalculate='Recalcular',
            noRate='No hay tarifa disponible para esta ruta',
            noRateHint='Envíe una consulta para recibir una cotización manual de nuestro equipo.',
            requestManual='Solicitar Cotización Manual',
            initialEstimate='Estimación Inicial',
            dayUnit='días',
            validUntil='Válido hasta',
            selectEstimate='Seleccionar Esta Estimación',
            estimateNoticeShort='Esta es una estimación inicial. El precio final se confirma cuando admin/proveedor recibe confirmación de la naviera/socio.',
            estimateNoticeFull='Esta es una estimación inicial. El precio final se confirma cuando admin/proveedor recibe confirmación de la naviera, NVOCC, co-loader o socio.',
            breakdownTitle='Desglose de Estimación',
            totalBreakdown='Total Estimado',
            custNameRequired='El nombre del cliente es obligatorio',
            hsCodeOptional='HS Code (opcional)',
            requestFinalQuote='Solicitar Cotización Final',
        ),
    },
    # ── French ────────────────────────────────────────────────────────────────
    'fr-FR': {
        'svc': dict(
            back='Retour',
            serviceUnit='service',
            realtimeUpdated='Mis à jour',
            realtimeLive='En direct',
            truckingBannerTitle='Réservez une flotte de camions directement',
            truckingBannerDesc="Choisissez parmi 12 types de flotte, vérifiez le coût d'expédition instantanément et ajoutez des services selon vos besoins. Simple et transparent.",
            truckingBannerCta='Vérifier le coût & réserver',
            folderViewContents='Voir le contenu',
            folderMore='autres',
            truckingBannerBadge='Réservation camion',
            folderCardDesc="Services de transport terrestre et location de conteneurs pour les livraisons locales et interurbaines.",
            folderViewAll='Voir tous les services',
            sellingPrice='Prix de vente',
            dialogSub='Choisissez le service qui correspond à vos besoins',
        ),
        'of': dict(
            successDesc="Votre demande de devis Ocean Freight a été envoyée. Notre équipe enverra le prix final après confirmation de la compagnie maritime / partenaire.",
            backToHome="Retour à l'accueil",
            yourData='Vos données',
            customerNameLabel='Nom',
            customerNamePlaceholder='Nom complet',
            customerPhoneLabel='Téléphone / WhatsApp',
            customerCompanyLabel='Entreprise',
            customerNotesLabel='Notes supplémentaires',
            customerNotesPlaceholder='Instructions spéciales...',
            goBack='Retour',
            sending='Envoi en cours...',
            koliQty='Nombre de colis',
            containerFinalNote='Détails finaux selon confirmation du transporteur.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Tarif basé sur le CBM utilisé',
            checkEstimate="Calculer l'estimation",
            calculating='Calcul en cours...',
            estimateResults="Résultats de l'estimation",
            recalculate='Recalculer',
            noRate='Aucun tarif disponible pour cet itinéraire',
            noRateHint='Veuillez soumettre une demande pour obtenir un devis manuel de notre équipe.',
            requestManual='Demander un devis manuel',
            initialEstimate='Estimation initiale',
            dayUnit='jours',
            validUntil="Valable jusqu'au",
            selectEstimate='Sélectionner cette estimation',
            estimateNoticeShort="Il s'agit d'une estimation initiale. Le prix final est confirmé après que l'admin/fournisseur reçoit la confirmation de la compagnie maritime/partenaire.",
            estimateNoticeFull="Il s'agit d'une estimation initiale. Le prix final est confirmé après confirmation de la compagnie maritime, NVOCC, co-loader ou partenaire.",
            breakdownTitle="Détail de l'estimation",
            totalBreakdown='Total estimé',
            custNameRequired='Le nom du client est obligatoire',
            hsCodeOptional='HS Code (facultatif)',
            requestFinalQuote='Demander le devis final',
        ),
    },
    # ── Hindi ─────────────────────────────────────────────────────────────────
    'hi-IN': {
        'svc': dict(
            back='वापस',
            serviceUnit='सेवा',
            realtimeUpdated='अपडेट किया गया',
            realtimeLive='लाइव',
            truckingBannerTitle='ट्रकिंग फ्लीट सीधे बुक करें',
            truckingBannerDesc='12 फ्लीट प्रकारों में से चुनें, तुरंत शिपिंग लागत जांचें, और आवश्यकतानुसार सेवाएं जोड़ें। आसान और पारदर्शी।',
            truckingBannerCta='लागत जांचें और बुक करें',
            folderViewContents='सामग्री देखें',
            folderMore='और',
            truckingBannerBadge='ट्रकिंग बुकिंग',
            folderCardDesc='स्थानीय और अंतर-शहर डिलीवरी के लिए भूमि परिवहन और कंटेनर किराया सेवाएं।',
            folderViewAll='सभी सेवाएं देखें',
            sellingPrice='बिक्री मूल्य',
            dialogSub='वह सेवा चुनें जो आपकी आवश्यकताओं के अनुकूल हो',
        ),
        'of': dict(
            successDesc='आपकी Ocean Freight कोटेशन अनुरोध भेज दी गई है। हमारी टीम शिपिंग लाइन / पार्टनर से पुष्टि के बाद अंतिम मूल्य भेजेगी।',
            backToHome='होम पर वापस जाएं',
            yourData='आपका डेटा',
            customerNameLabel='नाम',
            customerNamePlaceholder='पूरा नाम',
            customerPhoneLabel='फ़ोन / WhatsApp',
            customerCompanyLabel='कंपनी',
            customerNotesLabel='अतिरिक्त नोट्स',
            customerNotesPlaceholder='विशेष निर्देश...',
            goBack='वापस',
            sending='भेजा जा रहा है...',
            koliQty='पैकेजों की संख्या',
            containerFinalNote='अंतिम विवरण वाहक पुष्टि के अनुसार।',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='दर उपयोग किए गए CBM पर आधारित',
            checkEstimate='अनुमान जांचें',
            calculating='गणना हो रही है...',
            estimateResults='अनुमान परिणाम',
            recalculate='पुनर्गणना करें',
            noRate='इस मार्ग के लिए कोई दर उपलब्ध नहीं',
            noRateHint='हमारी टीम से मैन्युअल कोटेशन प्राप्त करने के लिए पूछताछ सबमिट करें।',
            requestManual='मैन्युअल कोटेशन अनुरोध',
            initialEstimate='प्रारंभिक अनुमान',
            dayUnit='दिन',
            validUntil='तक वैध',
            selectEstimate='यह अनुमान चुनें',
            estimateNoticeShort='यह प्रारंभिक अनुमान है। अंतिम मूल्य की पुष्टि तब होती है जब admin/vendor को शिपिंग लाइन/पार्टनर से पुष्टि मिलती है।',
            estimateNoticeFull='यह प्रारंभिक अनुमान है। अंतिम मूल्य की पुष्टि शिपिंग लाइन, NVOCC, co-loader या पार्टनर से पुष्टि के बाद होती है।',
            breakdownTitle='अनुमान विवरण',
            totalBreakdown='कुल अनुमान',
            custNameRequired='ग्राहक का नाम आवश्यक है',
            hsCodeOptional='HS Code (वैकल्पिक)',
            requestFinalQuote='अंतिम कोटेशन अनुरोध',
        ),
    },
    # ── Italian ───────────────────────────────────────────────────────────────
    'it-IT': {
        'svc': dict(
            back='Indietro',
            serviceUnit='servizio',
            realtimeUpdated='Aggiornato',
            realtimeLive='In diretta',
            truckingBannerTitle='Prenota la flotta di trasporto direttamente',
            truckingBannerDesc='Scegli tra 12 tipi di flotta, verifica il costo di spedizione istantaneamente e aggiungi servizi secondo le tue esigenze. Semplice e trasparente.',
            truckingBannerCta='Verifica costo & prenota',
            folderViewContents='Visualizza contenuti',
            folderMore='altri',
            truckingBannerBadge='Prenotazione trasporto',
            folderCardDesc='Servizi di trasporto terrestre e noleggio container per consegne locali e intercittadine.',
            folderViewAll='Visualizza tutti i servizi',
            sellingPrice='Prezzo di vendita',
            dialogSub='Scegli il servizio più adatto alle tue esigenze',
        ),
        'of': dict(
            successDesc='La tua richiesta di preventivo Ocean Freight è stata inviata. Il nostro team invierà il prezzo finale dopo la conferma della compagnia marittima / partner.',
            backToHome='Torna alla home',
            yourData='I tuoi dati',
            customerNameLabel='Nome',
            customerNamePlaceholder='Nome completo',
            customerPhoneLabel='Telefono / WhatsApp',
            customerCompanyLabel='Azienda',
            customerNotesLabel='Note aggiuntive',
            customerNotesPlaceholder='Istruzioni speciali...',
            goBack='Indietro',
            sending='Invio in corso...',
            koliQty='Numero di colli',
            containerFinalNote='Dettagli finali secondo conferma del vettore.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Tariffa basata sul CBM utilizzato',
            checkEstimate='Calcola stima',
            calculating='Calcolo in corso...',
            estimateResults='Risultati stima',
            recalculate='Ricalcola',
            noRate='Nessuna tariffa disponibile per questo percorso',
            noRateHint='Invia una richiesta per ricevere un preventivo manuale dal nostro team.',
            requestManual='Richiedi preventivo manuale',
            initialEstimate='Stima iniziale',
            dayUnit='giorni',
            validUntil='Valido fino al',
            selectEstimate='Seleziona questa stima',
            estimateNoticeShort='Questa è una stima iniziale. Il prezzo finale viene confermato dopo che admin/fornitore riceve conferma dalla compagnia marittima/partner.',
            estimateNoticeFull='Questa è una stima iniziale. Il prezzo finale viene confermato dopo conferma da compagnia marittima, NVOCC, co-loader o partner.',
            breakdownTitle='Dettaglio stima',
            totalBreakdown='Totale stimato',
            custNameRequired='Il nome del cliente è obbligatorio',
            hsCodeOptional='HS Code (facoltativo)',
            requestFinalQuote='Richiedi preventivo finale',
        ),
    },
    # ── Japanese ──────────────────────────────────────────────────────────────
    'ja-JP': {
        'svc': dict(
            back='戻る',
            serviceUnit='サービス',
            realtimeUpdated='更新済み',
            realtimeLive='ライブ',
            truckingBannerTitle='トラック輸送フリートを直接予約',
            truckingBannerDesc='12種類のフリートから選び、即座に運賃を確認し、必要に応じてサービスを追加できます。簡単で透明。',
            truckingBannerCta='料金確認＆予約',
            folderViewContents='内容を見る',
            folderMore='その他',
            truckingBannerBadge='トラック予約',
            folderCardDesc='ローカルおよび都市間配送のための陸上輸送とコンテナレンタルサービス。',
            folderViewAll='すべてのサービスを見る',
            sellingPrice='販売価格',
            dialogSub='ニーズに合ったサービスをお選びください',
        ),
        'of': dict(
            successDesc='Ocean Freight見積もりリクエストが送信されました。当社チームは船会社/パートナーの確認後に最終価格をお送りします。',
            backToHome='ホームに戻る',
            yourData='お客様情報',
            customerNameLabel='氏名',
            customerNamePlaceholder='フルネーム',
            customerPhoneLabel='電話番号 / WhatsApp',
            customerCompanyLabel='会社名',
            customerNotesLabel='追加メモ',
            customerNotesPlaceholder='特別な指示...',
            goBack='戻る',
            sending='送信中...',
            koliQty='梱包数',
            containerFinalNote='最終詳細はキャリアの確認に従います。',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='料金は使用CBMに基づく',
            checkEstimate='見積もり計算',
            calculating='計算中...',
            estimateResults='見積もり結果',
            recalculate='再計算',
            noRate='この路線の料金はありません',
            noRateHint='当社チームによる手動見積もりを取得するためにお問い合わせください。',
            requestManual='手動見積もり依頼',
            initialEstimate='初期見積もり',
            dayUnit='日',
            validUntil='有効期限',
            selectEstimate='この見積もりを選択',
            estimateNoticeShort='これは初期見積もりです。最終価格はadmin/ベンダーが船会社/パートナーの確認を受けた後に確定します。',
            estimateNoticeFull='これは初期見積もりです。最終価格は船会社、NVOCC、co-loader、またはパートナーの確認後に確定します。',
            breakdownTitle='見積もり内訳',
            totalBreakdown='見積もり合計',
            custNameRequired='お客様名は必須です',
            hsCodeOptional='HS Code（任意）',
            requestFinalQuote='最終見積もり依頼',
        ),
    },
    # ── Korean ────────────────────────────────────────────────────────────────
    'ko-KR': {
        'svc': dict(
            back='뒤로',
            serviceUnit='서비스',
            realtimeUpdated='업데이트됨',
            realtimeLive='라이브',
            truckingBannerTitle='트럭킹 차량 직접 예약',
            truckingBannerDesc='12가지 차량 유형 중 선택하고, 즉시 운임을 확인하고, 필요에 따라 서비스를 추가하세요. 쉽고 투명합니다.',
            truckingBannerCta='비용 확인 & 예약',
            folderViewContents='내용 보기',
            folderMore='더 보기',
            truckingBannerBadge='트럭킹 예약',
            folderCardDesc='로컬 및 도시 간 배송을 위한 육상 운송 및 컨테이너 임대 서비스.',
            folderViewAll='모든 서비스 보기',
            sellingPrice='판매 가격',
            dialogSub='필요에 맞는 서비스를 선택하세요',
        ),
        'of': dict(
            successDesc='Ocean Freight 견적 요청이 전송되었습니다. 당사 팀이 선사/파트너 확인 후 최종 가격을 보내드립니다.',
            backToHome='홈으로 돌아가기',
            yourData='고객 정보',
            customerNameLabel='이름',
            customerNamePlaceholder='전체 이름',
            customerPhoneLabel='전화번호 / WhatsApp',
            customerCompanyLabel='회사',
            customerNotesLabel='추가 메모',
            customerNotesPlaceholder='특별 지시사항...',
            goBack='뒤로',
            sending='전송 중...',
            koliQty='포장 수량',
            containerFinalNote='최종 세부 사항은 운송사 확인에 따릅니다.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='요금은 사용된 CBM 기준',
            checkEstimate='견적 계산',
            calculating='계산 중...',
            estimateResults='견적 결과',
            recalculate='재계산',
            noRate='이 노선에 사용 가능한 요금 없음',
            noRateHint='당사 팀으로부터 수동 견적을 받으려면 문의를 제출하세요.',
            requestManual='수동 견적 요청',
            initialEstimate='초기 견적',
            dayUnit='일',
            validUntil='유효 기간',
            selectEstimate='이 견적 선택',
            estimateNoticeShort='이는 초기 견적입니다. 최종 가격은 admin/공급업체가 선사/파트너로부터 확인을 받은 후 확정됩니다.',
            estimateNoticeFull='이는 초기 견적입니다. 최종 가격은 선사, NVOCC, co-loader 또는 파트너로부터 확인 후 확정됩니다.',
            breakdownTitle='견적 내역',
            totalBreakdown='견적 합계',
            custNameRequired='고객 이름은 필수입니다',
            hsCodeOptional='HS Code (선택사항)',
            requestFinalQuote='최종 견적 요청',
        ),
    },
    # ── Malay ─────────────────────────────────────────────────────────────────
    'ms-MY': {
        'svc': dict(
            back='Kembali',
            serviceUnit='perkhidmatan',
            realtimeUpdated='Dikemas kini',
            realtimeLive='Langsung',
            truckingBannerTitle='Tempah Armada Trak Terus',
            truckingBannerDesc='Pilih daripada 12 jenis armada, semak kos penghantaran segera, dan tambah perkhidmatan mengikut keperluan. Mudah dan telus.',
            truckingBannerCta='Semak Kos & Tempah',
            folderViewContents='Lihat Kandungan',
            folderMore='lagi',
            truckingBannerBadge='Tempahan Trak',
            folderCardDesc='Perkhidmatan pengangkutan darat dan sewa kontena untuk penghantaran tempatan dan antara bandar.',
            folderViewAll='Lihat Semua Perkhidmatan',
            sellingPrice='Harga Jualan',
            dialogSub='Pilih perkhidmatan yang sesuai dengan keperluan anda',
        ),
        'of': dict(
            successDesc='Permintaan sebut harga Ocean Freight anda telah dihantar. Pasukan kami akan menghantar harga akhir selepas pengesahan daripada syarikat perkapalan / rakan kongsi.',
            backToHome='Kembali ke Laman Utama',
            yourData='Data Anda',
            customerNameLabel='Nama',
            customerNamePlaceholder='Nama penuh',
            customerPhoneLabel='Telefon / WhatsApp',
            customerCompanyLabel='Syarikat',
            customerNotesLabel='Nota Tambahan',
            customerNotesPlaceholder='Arahan khas...',
            goBack='Kembali',
            sending='Menghantar...',
            koliQty='Bilangan Pakej',
            containerFinalNote='Butiran akhir mengikut pengesahan pengangkut.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Kadar berdasarkan CBM yang digunakan',
            checkEstimate='Kira Anggaran',
            calculating='Sedang mengira...',
            estimateResults='Keputusan Anggaran',
            recalculate='Kira Semula',
            noRate='Tiada kadar tersedia untuk laluan ini',
            noRateHint='Sila hantar pertanyaan untuk mendapatkan sebut harga manual daripada pasukan kami.',
            requestManual='Minta Sebut Harga Manual',
            initialEstimate='Anggaran Awal',
            dayUnit='hari',
            validUntil='Sah sehingga',
            selectEstimate='Pilih Anggaran Ini',
            estimateNoticeShort='Ini adalah anggaran awal. Harga akhir disahkan selepas admin/vendor menerima pengesahan daripada syarikat perkapalan/rakan kongsi.',
            estimateNoticeFull='Ini adalah anggaran awal. Harga akhir disahkan selepas pengesahan daripada syarikat perkapalan, NVOCC, co-loader, atau rakan kongsi.',
            breakdownTitle='Pecahan Anggaran',
            totalBreakdown='Jumlah Anggaran',
            custNameRequired='Nama pelanggan diperlukan',
            hsCodeOptional='HS Code (pilihan)',
            requestFinalQuote='Minta Sebut Harga Akhir',
        ),
    },
    # ── Dutch ─────────────────────────────────────────────────────────────────
    'nl-NL': {
        'svc': dict(
            back='Terug',
            serviceUnit='dienst',
            realtimeUpdated='Bijgewerkt',
            realtimeLive='Live',
            truckingBannerTitle='Boek Transportvloot Rechtstreeks',
            truckingBannerDesc='Kies uit 12 typen vloten, controleer direct de verzendkosten en voeg diensten toe op basis van uw behoeften. Eenvoudig en transparant.',
            truckingBannerCta='Kosten controleren & boeken',
            folderViewContents='Inhoud bekijken',
            folderMore='meer',
            truckingBannerBadge='Transport boeking',
            folderCardDesc='Landtransport- en containerverhuurdiensten voor lokale en intercity leveringsbehoeften.',
            folderViewAll='Alle diensten bekijken',
            sellingPrice='Verkoopprijs',
            dialogSub='Kies de dienst die past bij uw behoeften',
        ),
        'of': dict(
            successDesc='Uw Ocean Freight-offerteaanvraag is verzonden. Ons team stuurt de definitieve prijs na bevestiging van de rederij / partner.',
            backToHome='Terug naar home',
            yourData='Uw gegevens',
            customerNameLabel='Naam',
            customerNamePlaceholder='Volledige naam',
            customerPhoneLabel='Telefoon / WhatsApp',
            customerCompanyLabel='Bedrijf',
            customerNotesLabel='Aanvullende opmerkingen',
            customerNotesPlaceholder='Speciale instructies...',
            goBack='Terug',
            sending='Verzenden...',
            koliQty='Aantal colli',
            containerFinalNote='Definitieve details conform bevestiging van de vervoerder.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Tarief gebaseerd op gebruikte CBM',
            checkEstimate='Schatting berekenen',
            calculating='Berekenen...',
            estimateResults='Schattingsresultaten',
            recalculate='Opnieuw berekenen',
            noRate='Geen tarief beschikbaar voor deze route',
            noRateHint='Dien een aanvraag in voor een handmatige offerte van ons team.',
            requestManual='Handmatige offerte aanvragen',
            initialEstimate='Eerste schatting',
            dayUnit='dagen',
            validUntil='Geldig tot',
            selectEstimate='Deze schatting selecteren',
            estimateNoticeShort='Dit is een eerste schatting. De definitieve prijs wordt bevestigd nadat admin/leverancier bevestiging ontvangt van de rederij/partner.',
            estimateNoticeFull='Dit is een eerste schatting. De definitieve prijs wordt bevestigd na bevestiging van de rederij, NVOCC, co-loader of partner.',
            breakdownTitle='Schattingsoverzicht',
            totalBreakdown='Totale schatting',
            custNameRequired='Klantnaam is verplicht',
            hsCodeOptional='HS Code (optioneel)',
            requestFinalQuote='Definitieve offerte aanvragen',
        ),
    },
    # ── Simplified Chinese ────────────────────────────────────────────────────
    'zh-CN': {
        'svc': dict(
            back='返回',
            serviceUnit='项服务',
            realtimeUpdated='已更新',
            realtimeLive='实时',
            truckingBannerTitle='直接预订卡车运输车队',
            truckingBannerDesc='从12种车型中选择，立即查询运费，按需添加服务。简单透明。',
            truckingBannerCta='查询费用并预订',
            folderViewContents='查看内容',
            folderMore='更多',
            truckingBannerBadge='卡车预订',
            folderCardDesc='提供本地及城际配送的陆路运输和集装箱租赁服务。',
            folderViewAll='查看全部服务',
            sellingPrice='售价',
            dialogSub='选择适合您需求的服务',
        ),
        'of': dict(
            successDesc='您的海运报价请求已发送。我们的团队将在获得船公司/合作伙伴确认后发送最终价格。',
            backToHome='返回首页',
            yourData='您的信息',
            customerNameLabel='姓名',
            customerNamePlaceholder='全名',
            customerPhoneLabel='电话 / WhatsApp',
            customerCompanyLabel='公司',
            customerNotesLabel='附加备注',
            customerNotesPlaceholder='特殊说明...',
            goBack='返回',
            sending='发送中...',
            koliQty='包裹数量',
            containerFinalNote='最终详情以承运人确认为准。',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='费率基于已使用的CBM',
            checkEstimate='计算估算',
            calculating='计算中...',
            estimateResults='估算结果',
            recalculate='重新计算',
            noRate='此路线暂无可用费率',
            noRateHint='请提交询价，获取我们团队的人工报价。',
            requestManual='申请人工报价',
            initialEstimate='初步估算',
            dayUnit='天',
            validUntil='有效期至',
            selectEstimate='选择此估算',
            estimateNoticeShort='此为初步估算。最终价格在管理员/供应商收到船公司/合作伙伴确认后确定。',
            estimateNoticeFull='此为初步估算。最终价格在收到船公司、NVOCC、拼箱商或合作伙伴确认后确定。',
            breakdownTitle='估算明细',
            totalBreakdown='估算总计',
            custNameRequired='客户姓名为必填项',
            hsCodeOptional='HS Code（可选）',
            requestFinalQuote='申请最终报价',
        ),
    },
    # ── Traditional Chinese ───────────────────────────────────────────────────
    'zh-TW': {
        'svc': dict(
            back='返回',
            serviceUnit='項服務',
            realtimeUpdated='已更新',
            realtimeLive='即時',
            truckingBannerTitle='直接預訂貨車運輸車隊',
            truckingBannerDesc='從12種車型中選擇，立即查詢運費，按需添加服務。簡單透明。',
            truckingBannerCta='查詢費用並預訂',
            folderViewContents='查看內容',
            folderMore='更多',
            truckingBannerBadge='貨車預訂',
            folderCardDesc='提供本地及城際配送的陸路運輸和貨櫃租賃服務。',
            folderViewAll='查看全部服務',
            sellingPrice='售價',
            dialogSub='選擇適合您需求的服務',
        ),
        'of': dict(
            successDesc='您的海運報價請求已發送。我們的團隊將在獲得船公司/合作夥伴確認後發送最終價格。',
            backToHome='返回首頁',
            yourData='您的資料',
            customerNameLabel='姓名',
            customerNamePlaceholder='全名',
            customerPhoneLabel='電話 / WhatsApp',
            customerCompanyLabel='公司',
            customerNotesLabel='附加備注',
            customerNotesPlaceholder='特殊說明...',
            goBack='返回',
            sending='發送中...',
            koliQty='包裹數量',
            containerFinalNote='最終詳情以承運人確認為準。',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='費率基於已使用的CBM',
            checkEstimate='計算估算',
            calculating='計算中...',
            estimateResults='估算結果',
            recalculate='重新計算',
            noRate='此路線暫無可用費率',
            noRateHint='請提交詢價，獲取我們團隊的人工報價。',
            requestManual='申請人工報價',
            initialEstimate='初步估算',
            dayUnit='天',
            validUntil='有效期至',
            selectEstimate='選擇此估算',
            estimateNoticeShort='此為初步估算。最終價格在管理員/供應商收到船公司/合作夥伴確認後確定。',
            estimateNoticeFull='此為初步估算。最終價格在收到船公司、NVOCC、拼箱商或合作夥伴確認後確定。',
            breakdownTitle='估算明細',
            totalBreakdown='估算總計',
            custNameRequired='客戶姓名為必填項',
            hsCodeOptional='HS Code（可選）',
            requestFinalQuote='申請最終報價',
        ),
    },
    # ── English AU ────────────────────────────────────────────────────────────
    'en-AU': {
        'svc': dict(
            back='Back',
            serviceUnit='service',
            realtimeUpdated='Updated',
            realtimeLive='Live',
            truckingBannerTitle='Book Trucking Fleet Directly',
            truckingBannerDesc='Choose from 12 fleet types, check instant shipping cost, and add services as needed. Easy and transparent.',
            truckingBannerCta='Check Cost & Book',
            folderViewContents='View Contents',
            folderMore='more',
            truckingBannerBadge='Trucking Booking',
            folderCardDesc='Land transport and container rental services for local and inter-city delivery needs.',
            folderViewAll='View All Services',
            sellingPrice='Selling Price',
            dialogSub='Choose the service that fits your needs',
        ),
        'of': dict(
            successDesc='Your Ocean Freight quote request has been submitted. Our team will send the final price after confirmation from the shipping line / partner.',
            backToHome='Back to Home',
            yourData='Your Details',
            customerNameLabel='Name',
            customerNamePlaceholder='Full name',
            customerPhoneLabel='Phone / WhatsApp',
            customerCompanyLabel='Company',
            customerNotesLabel='Additional Notes',
            customerNotesPlaceholder='Special instructions...',
            goBack='Back',
            sending='Sending...',
            koliQty='Number of Packages',
            containerFinalNote='Final details subject to carrier confirmation.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Rate based on filled CBM',
            checkEstimate='Check Estimate',
            calculating='Calculating...',
            estimateResults='Estimate Results',
            recalculate='Recalculate',
            noRate='No rate available for this route',
            noRateHint='Please submit an inquiry to receive a manual quote from our team.',
            requestManual='Request Manual Quote',
            initialEstimate='Initial Estimate',
            dayUnit='days',
            validUntil='Valid until',
            selectEstimate='Select This Estimate',
            estimateNoticeShort='This is an initial estimate. The final price is confirmed after admin/vendor receives confirmation from the shipping line/partner.',
            estimateNoticeFull='This is an initial estimate. The final price is confirmed after confirmation from the shipping line, NVOCC, co-loader, or partner.',
            breakdownTitle='Estimate Breakdown',
            totalBreakdown='Total Estimate',
            custNameRequired='Customer name is required',
            hsCodeOptional='HS Code (optional)',
            requestFinalQuote='Request Final Quote',
        ),
    },
    # ── English GB ────────────────────────────────────────────────────────────
    'en-GB': {
        'svc': dict(
            back='Back',
            serviceUnit='service',
            realtimeUpdated='Updated',
            realtimeLive='Live',
            truckingBannerTitle='Book Trucking Fleet Directly',
            truckingBannerDesc='Choose from 12 fleet types, check instant shipping cost, and add services as needed. Easy and transparent.',
            truckingBannerCta='Check Cost & Book',
            folderViewContents='View Contents',
            folderMore='more',
            truckingBannerBadge='Trucking Booking',
            folderCardDesc='Road transport and container hire services for local and inter-city delivery needs.',
            folderViewAll='View All Services',
            sellingPrice='Selling Price',
            dialogSub='Choose the service that fits your needs',
        ),
        'of': dict(
            successDesc='Your Ocean Freight quote request has been submitted. Our team will send the final price after confirmation from the shipping line / partner.',
            backToHome='Back to Home',
            yourData='Your Details',
            customerNameLabel='Name',
            customerNamePlaceholder='Full name',
            customerPhoneLabel='Phone / WhatsApp',
            customerCompanyLabel='Company',
            customerNotesLabel='Additional Notes',
            customerNotesPlaceholder='Special instructions...',
            goBack='Back',
            sending='Sending...',
            koliQty='Number of Packages',
            containerFinalNote='Final details subject to carrier confirmation.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Rate based on filled CBM',
            checkEstimate='Check Estimate',
            calculating='Calculating...',
            estimateResults='Estimate Results',
            recalculate='Recalculate',
            noRate='No rate available for this route',
            noRateHint='Please submit an enquiry to receive a manual quote from our team.',
            requestManual='Request Manual Quote',
            initialEstimate='Initial Estimate',
            dayUnit='days',
            validUntil='Valid until',
            selectEstimate='Select This Estimate',
            estimateNoticeShort='This is an initial estimate. The final price is confirmed after admin/vendor receives confirmation from the shipping line/partner.',
            estimateNoticeFull='This is an initial estimate. The final price is confirmed after confirmation from the shipping line, NVOCC, co-loader, or partner.',
            breakdownTitle='Estimate Breakdown',
            totalBreakdown='Total Estimate',
            custNameRequired='Customer name is required',
            hsCodeOptional='HS Code (optional)',
            requestFinalQuote='Request Final Quote',
        ),
    },
    # ── English SG ────────────────────────────────────────────────────────────
    'en-SG': {
        'svc': dict(
            back='Back',
            serviceUnit='service',
            realtimeUpdated='Updated',
            realtimeLive='Live',
            truckingBannerTitle='Book Trucking Fleet Directly',
            truckingBannerDesc='Choose from 12 fleet types, check instant shipping cost, and add services as needed. Easy and transparent.',
            truckingBannerCta='Check Cost & Book',
            folderViewContents='View Contents',
            folderMore='more',
            truckingBannerBadge='Trucking Booking',
            folderCardDesc='Land transport and container rental services for local and inter-city delivery needs.',
            folderViewAll='View All Services',
            sellingPrice='Selling Price',
            dialogSub='Choose the service that fits your needs',
        ),
        'of': dict(
            successDesc='Your Ocean Freight quote request has been submitted. Our team will send the final price after confirmation from the shipping line / partner.',
            backToHome='Back to Home',
            yourData='Your Details',
            customerNameLabel='Name',
            customerNamePlaceholder='Full name',
            customerPhoneLabel='Phone / WhatsApp',
            customerCompanyLabel='Company',
            customerNotesLabel='Additional Notes',
            customerNotesPlaceholder='Special instructions...',
            goBack='Back',
            sending='Sending...',
            koliQty='Number of Packages',
            containerFinalNote='Final details subject to carrier confirmation.',
            lclCargo='LCL Cargo',
            lclCargoSub='Less than Container Load',
            lclRateNote='Rate based on filled CBM',
            checkEstimate='Check Estimate',
            calculating='Calculating...',
            estimateResults='Estimate Results',
            recalculate='Recalculate',
            noRate='No rate available for this route',
            noRateHint='Please submit an inquiry to receive a manual quote from our team.',
            requestManual='Request Manual Quote',
            initialEstimate='Initial Estimate',
            dayUnit='days',
            validUntil='Valid until',
            selectEstimate='Select This Estimate',
            estimateNoticeShort='This is an initial estimate. The final price is confirmed after admin/vendor receives confirmation from the shipping line/partner.',
            estimateNoticeFull='This is an initial estimate. The final price is confirmed after confirmation from the shipping line, NVOCC, co-loader, or partner.',
            breakdownTitle='Estimate Breakdown',
            totalBreakdown='Total Estimate',
            custNameRequired='Customer name is required',
            hsCodeOptional='HS Code (optional)',
            requestFinalQuote='Request Final Quote',
        ),
    },
}

# ── Helper: escape a value for TypeScript single-quoted string ────────────────
def ts_val(v):
    """Escape value for use inside TypeScript single-quoted string."""
    return v.replace("\\", "\\\\").replace("'", "\\'")

# ── Helper: build the insertion block ─────────────────────────────────────────
def build_svc_block(t):
    lines = []
    for k, v in t.items():
        lines.append(f"    {k}: '{ts_val(v)}',")
    return '\n'.join(lines)

def build_of_block(t):
    lines = []
    for k, v in t.items():
        lines.append(f"    {k}: '{ts_val(v)}',")
    return '\n'.join(lines)

# ── Apply insertions to a single locale file ──────────────────────────────────
def patch_locale(locale_code):
    fname = f'{locale_code}.ts'
    path = os.path.join(LOCALES_DIR, fname)
    with open(path, encoding='utf-8') as f:
        src = f.read()
    original = src
    tr = TRANSLATIONS[locale_code]

    # 1. Services insertion: after `    tryOther: '...',` + newline, before `  },`
    # Pattern: find the line with tryOther: in services section followed by `  },`
    # We use a regex that matches `    tryOther: '...',\n  },`
    svc_block = build_svc_block(tr['svc'])
    # Match tryOther line followed immediately by  },
    svc_pattern = r"(    tryOther: '[^']*',\s*\n)(  },)"
    svc_replacement = r"\g<1>" + svc_block + "\n" + r"\g<2>"
    new_src = re.sub(svc_pattern, svc_replacement, src, count=1)
    if new_src == src:
        print(f"  WARNING [{fname}]: services tryOther anchor not found", file=sys.stderr)
    else:
        src = new_src

    # 2. OceanFreight insertion: after `    ctaWa: '...',` + newline, before `  },`
    of_block = build_of_block(tr['of'])
    of_pattern = r"(    ctaWa: '[^']*',\s*\n)(  },)"
    of_replacement = r"\g<1>" + of_block + "\n" + r"\g<2>"
    new_src = re.sub(of_pattern, of_replacement, src, count=1)
    if new_src == src:
        print(f"  WARNING [{fname}]: oceanFreight ctaWa anchor not found", file=sys.stderr)
    else:
        src = new_src

    if src == original:
        print(f"  [{fname}] no changes (already patched?)")
        return

    with open(path, 'w', encoding='utf-8') as f:
        f.write(src)
    print(f"  [{fname}] inserted {len(tr['svc'])} services keys + {len(tr['of'])} oceanFreight keys")

# ── Run for all 16 locales ────────────────────────────────────────────────────
LOCALES = [
    'ar-AE', 'ar-SA', 'de-DE', 'es-ES', 'fr-FR', 'hi-IN',
    'it-IT', 'ja-JP', 'ko-KR', 'ms-MY', 'nl-NL', 'zh-CN',
    'zh-TW', 'en-AU', 'en-GB', 'en-SG',
]

for lc in LOCALES:
    patch_locale(lc)

print("\n✅ Done — 48 keys inserted into 16 locale files.")
