// Browser-safe copy of SERVICE_SCHEMAS — extracted from artifacts/api-server/src/routes/vendorMiniForm.ts
// The API server file has Express/Drizzle imports that cannot be bundled for the browser.
// Keep this in sync with the source of truth in the API server file.

export const SERVICE_SCHEMAS: Record<string, {
  label: string; emoji: string;
  fields: {
    key: string; label: string;
    type: "text" | "number" | "select" | "textarea" | "date";
    options?: string[]; required?: boolean; placeholder?: string;
    section?: "quotation" | "operational" | "both";
    isUpload?: boolean;
  }[];
}> = {
  product: {
    label: "Produk", emoji: "📦",
    fields: [
      { key: "product_name", label: "Nama Produk", type: "text", required: true, section: "both" },
      { key: "brand", label: "Brand / Spesifikasi", type: "text", section: "quotation" },
      { key: "unit_price", label: "Harga per Satuan (Rp)", type: "number", required: true, section: "quotation" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["IDR", "USD", "SGD", "EUR"], section: "quotation" },
      { key: "qty_available", label: "Qty Tersedia", type: "number", section: "quotation" },
      { key: "min_order", label: "Minimum Order", type: "number", section: "quotation" },
      { key: "unit", label: "Satuan", type: "select", options: ["pcs", "kg", "ton", "box", "karton", "lusin", "unit"], required: true, section: "both" },
      { key: "lead_time", label: "Lead Time (hari)", type: "number", section: "quotation" },
      { key: "stock_status", label: "Status Stok", type: "select", options: ["Ready Stock", "Indent", "Pre-order"], section: "quotation" },
      { key: "valid_until", label: "Harga Berlaku Sampai", type: "date", section: "quotation" },
      { key: "eta", label: "Estimasi Pengiriman (hari)", type: "text", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "both" },
      // Operational fields
      { key: "stock_confirmation", label: "Konfirmasi Stok", type: "select", options: ["Ready", "Partially Ready", "Indent"], section: "operational" },
      { key: "packing_confirmation", label: "Status Packing", type: "select", options: ["Belum Packing", "Sedang Packing", "Sudah Packing"], section: "operational" },
      { key: "delivery_schedule", label: "Jadwal Pengiriman", type: "text", section: "operational" },
      { key: "invoice_vendor", label: "No. Invoice Vendor", type: "text", section: "operational" },
    ],
  },
  trucking: {
    label: "Trucking", emoji: "🚛",
    fields: [
      { key: "truck_type", label: "Jenis Armada", type: "select", required: true, options: ["CDD", "CDE", "Fuso", "Tronton", "Trailer 20ft", "Trailer 40ft", "Pick Up", "Box Truck"], section: "quotation" },
      { key: "capacity", label: "Kapasitas (ton)", type: "number", section: "quotation" },
      { key: "area_pickup", label: "Area Pickup", type: "text", required: true, placeholder: "Contoh: Cilincing, Jakarta Utara", section: "quotation" },
      { key: "area_delivery", label: "Area Delivery", type: "text", required: true, placeholder: "Contoh: Cibitung, Bekasi", section: "quotation" },
      { key: "price", label: "Harga Trucking (Rp)", type: "number", required: true, section: "quotation" },
      { key: "additional_charge", label: "Biaya Tambahan (Rp)", type: "number", placeholder: "Kosongkan jika tidak ada", section: "quotation" },
      { key: "eta_pickup", label: "Estimasi Pickup", type: "text", placeholder: "Contoh: H+1 setelah konfirmasi", section: "quotation" },
      { key: "eta_delivery", label: "Estimasi Delivery", type: "text", placeholder: "Contoh: 1–2 hari setelah pickup", section: "quotation" },
      { key: "valid_until", label: "Rate Berlaku Sampai", type: "date", section: "quotation" },
      { key: "notes", label: "Catatan Penawaran", type: "textarea", section: "quotation" },
      // Operational
      { key: "driver_name", label: "Nama Driver", type: "text", required: true, section: "operational" },
      { key: "driver_phone", label: "No HP Driver", type: "text", required: true, section: "operational" },
      { key: "plate_number", label: "Plat Nomor Kendaraan", type: "text", required: true, section: "operational" },
      { key: "vehicle_type", label: "Jenis Kendaraan", type: "text", section: "operational" },
      { key: "pickup_time", label: "Waktu Pickup", type: "text", section: "operational" },
      { key: "delivery_time", label: "Waktu Delivery", type: "text", section: "operational" },
      { key: "op_notes", label: "Catatan Operasional", type: "textarea", section: "operational" },
    ],
  },
  sea_freight: {
    label: "Sea Freight", emoji: "🚢",
    fields: [
      { key: "shipping_line", label: "Shipping Line / Forwarder", type: "text", required: true, placeholder: "Contoh: Maersk, MSC", section: "quotation" },
      { key: "pol", label: "Port of Loading (POL)", type: "text", required: true, placeholder: "Contoh: IDJKT", section: "quotation" },
      { key: "pod", label: "Port of Discharge (POD)", type: "text", required: true, placeholder: "Contoh: SGSIN", section: "quotation" },
      { key: "container_type", label: "Tipe Kontainer", type: "select", required: true, options: ["20' GP", "40' GP", "40' HC", "45' HC", "20' RF", "40' RF"], section: "quotation" },
      { key: "freight_rate", label: "Freight Rate", type: "number", required: true, section: "quotation" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["USD", "IDR", "SGD", "EUR", "CNY"], required: true, section: "quotation" },
      { key: "etd", label: "ETD", type: "date", section: "quotation" },
      { key: "eta", label: "ETA", type: "date", section: "quotation" },
      { key: "transit_time", label: "Transit Time (hari)", type: "number", required: true, section: "quotation" },
      { key: "free_time", label: "Free Time Demurrage (hari)", type: "number", section: "quotation" },
      { key: "charges_include", label: "Include Charges", type: "textarea", placeholder: "Contoh: BL Fee, THC Origin", section: "quotation" },
      { key: "surcharge_note", label: "Surcharge / Additional", type: "textarea", section: "quotation" },
      { key: "validity", label: "Rate Berlaku Sampai", type: "date", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "quotation" },
      // Operational
      { key: "booking_number", label: "Booking Number", type: "text", required: true, section: "operational" },
      { key: "vessel_name", label: "Vessel / Kapal", type: "text", section: "operational" },
      { key: "op_etd", label: "ETD Aktual", type: "text", section: "operational" },
      { key: "op_eta", label: "ETA Aktual", type: "text", section: "operational" },
      { key: "bl_number", label: "BL Number", type: "text", section: "operational" },
    ],
  },
  air_freight: {
    label: "Air Freight", emoji: "✈️",
    fields: [
      { key: "airline", label: "Maskapai / Agent", type: "text", required: true, placeholder: "Contoh: Garuda Cargo, DHL", section: "quotation" },
      { key: "origin_airport", label: "Bandara Asal (IATA)", type: "text", required: true, placeholder: "Contoh: CGK", section: "quotation" },
      { key: "dest_airport", label: "Bandara Tujuan (IATA)", type: "text", required: true, placeholder: "Contoh: SIN", section: "quotation" },
      { key: "rate_per_kg", label: "Rate per kg", type: "number", required: true, section: "quotation" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["IDR", "USD", "SGD", "EUR", "CNY"], required: true, section: "quotation" },
      { key: "min_charge", label: "Minimum Charge", type: "number", section: "quotation" },
      { key: "fsc", label: "FSC / SSC / MYC", type: "text", placeholder: "Kosongkan jika tidak ada", section: "quotation" },
      { key: "etd", label: "ETD / Jadwal Penerbangan", type: "date", section: "quotation" },
      { key: "transit_time", label: "Transit Time (hari)", type: "number", required: true, section: "quotation" },
      { key: "chargeable_weight_rule", label: "Chargeable Weight Rule", type: "select", options: ["Actual Weight", "Volume Weight", "Higher of Both"], section: "quotation" },
      { key: "charges_include", label: "Include Charges", type: "textarea", section: "quotation" },
      { key: "validity", label: "Rate Berlaku Sampai", type: "date", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "quotation" },
      // Operational
      { key: "booking_number", label: "Booking Number", type: "text", required: true, section: "operational" },
      { key: "flight_number", label: "Nomor Penerbangan", type: "text", section: "operational" },
      { key: "op_etd", label: "ETD Aktual", type: "text", section: "operational" },
      { key: "op_eta", label: "ETA Aktual", type: "text", section: "operational" },
      { key: "awb_number", label: "AWB Number", type: "text", section: "operational" },
    ],
  },
  ppjk: {
    label: "PPJK / Customs Clearance", emoji: "📋",
    fields: [
      { key: "doc_type", label: "Jenis Dokumen BC", type: "select", required: true, options: ["PIB Jalur Hijau", "PIB Jalur Kuning", "PIB Jalur Merah", "PIB Jalur Prioritas", "PIBK", "PEB", "BCF"], section: "quotation" },
      { key: "hs_code", label: "HS Code (opsional)", type: "text", section: "quotation" },
      { key: "customs_service", label: "Estimasi Biaya Jasa", type: "number", required: true, section: "quotation" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["IDR", "USD"], required: true, section: "quotation" },
      { key: "duty_tax_estimate", label: "Estimasi Duty/Tax", type: "number", section: "quotation" },
      { key: "docs_required", label: "Dokumen yang Dibutuhkan", type: "textarea", section: "quotation" },
      { key: "sla", label: "SLA Proses (hari kerja)", type: "number", section: "quotation" },
      { key: "undername", label: "Biaya Undername (Rp)", type: "number", placeholder: "Kosongkan jika tidak ada", section: "quotation" },
      { key: "notes", label: "Catatan / Compliance", type: "textarea", section: "quotation" },
      // Operational
      { key: "nomor_aju", label: "Nomor Aju", type: "text", required: true, section: "operational" },
      { key: "jenis_dokumen", label: "Jenis Dokumen Aktual", type: "text", section: "operational" },
      { key: "status_customs", label: "Status Customs", type: "select", options: ["Dalam Proses", "Jalur Hijau", "Jalur Kuning", "Jalur Merah", "SPPB Terbit"], section: "operational" },
      { key: "billing_info", label: "Info Billing / Pajak", type: "textarea", section: "operational" },
    ],
  },
  handling: {
    label: "Handling / Warehouse", emoji: "🏭",
    fields: [
      { key: "location", label: "Lokasi Warehouse", type: "text", required: true, placeholder: "Contoh: Cikarang Barat", section: "quotation" },
      { key: "area_sqm", label: "Luas Tersedia (m²)", type: "number", section: "quotation" },
      { key: "handling_fee", label: "Handling Fee (Rp)", type: "number", required: true, section: "quotation" },
      { key: "storage_fee", label: "Storage Fee (Rp/m²/bulan)", type: "number", section: "quotation" },
      { key: "free_storage", label: "Free Storage (hari)", type: "number", section: "quotation" },
      { key: "loading_unloading_fee", label: "Loading/Unloading Fee (Rp/ton)", type: "number", section: "quotation" },
      { key: "temperature", label: "Suhu / Tipe", type: "select", options: ["Ambient", "Chilled (2–8°C)", "Frozen (-18°C)", "AC Room"], section: "quotation" },
      { key: "rack_system", label: "Sistem Racking", type: "select", options: ["Selective", "Drive-in", "Push Back", "Floor Storage", "Mezzanine"], section: "quotation" },
      { key: "sla", label: "SLA Proses (hari)", type: "number", section: "quotation" },
      { key: "equipment", label: "Equipment Support", type: "text", placeholder: "Contoh: Forklift 3 ton, CCTV 24 jam", section: "quotation" },
      { key: "security", label: "Keamanan", type: "text", placeholder: "Contoh: CCTV 24 jam, Satpam", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "quotation" },
      // Operational
      { key: "wh_receipt_number", label: "No. Warehouse Receipt", type: "text", required: true, section: "operational" },
      { key: "inbound_date", label: "Tanggal Inbound", type: "date", section: "operational" },
      { key: "qty_received", label: "Qty Diterima", type: "number", section: "operational" },
      { key: "condition_note", label: "Kondisi Barang", type: "textarea", section: "operational" },
      { key: "outbound_date", label: "Tanggal Outbound", type: "date", section: "operational" },
      { key: "op_notes", label: "Catatan Operasional", type: "textarea", section: "operational" },
    ],
  },
  document: {
    label: "Document / Additional Service", emoji: "📄",
    fields: [
      { key: "service_name", label: "Nama Layanan", type: "text", required: true, section: "quotation" },
      { key: "description", label: "Deskripsi Layanan", type: "textarea", section: "quotation" },
      { key: "price", label: "Harga", type: "number", required: true, section: "quotation" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["IDR", "USD"], required: true, section: "quotation" },
      { key: "sla", label: "SLA / Lead Time (hari)", type: "number", section: "quotation" },
      { key: "docs_required", label: "Dokumen yang Dibutuhkan", type: "textarea", section: "quotation" },
      { key: "validity", label: "Berlaku Sampai", type: "date", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "quotation" },
      // Operational
      { key: "doc_reference", label: "No. Referensi Dokumen", type: "text", required: true, section: "operational" },
      { key: "issue_date", label: "Tanggal Terbit", type: "date", section: "operational" },
      { key: "status_doc", label: "Status Dokumen", type: "select", options: ["Dalam Proses", "Selesai", "Ditolak", "Revisi"], section: "operational" },
      { key: "op_notes", label: "Catatan Operasional", type: "textarea", section: "operational" },
    ],
  },
  exim_service: {
    label: "Exim Service", emoji: "🌐",
    fields: [
      { key: "service_type", label: "Layanan", type: "select", required: true, options: ["Import Door to Door", "Export Door to Door", "Import Port to Port", "Export Port to Port", "Full Service"], section: "quotation" },
      { key: "origin_country", label: "Negara Asal", type: "text", required: true, section: "quotation" },
      { key: "dest_country", label: "Negara Tujuan", type: "text", required: true, section: "quotation" },
      { key: "price", label: "Harga", type: "number", required: true, section: "quotation" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["IDR", "USD", "SGD", "EUR", "CNY"], required: true, section: "quotation" },
      { key: "transit_time", label: "Transit Time (hari)", type: "number", section: "quotation" },
      { key: "incoterms", label: "Incoterms", type: "select", options: ["EXW", "FOB", "CIF", "DAP", "DDP", "FCA", "CPT", "CIP"], section: "quotation" },
      { key: "validity", label: "Masa Berlaku (hari)", type: "number", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "quotation" },
      // Operational
      { key: "job_reference", label: "No. Job Reference", type: "text", required: true, section: "operational" },
      { key: "shipment_status", label: "Status Shipment", type: "select", options: ["Booking", "In Transit Origin", "On Vessel/Flight", "Arrived Destination", "Customs Clearance", "Out for Delivery", "Delivered"], section: "operational" },
      { key: "actual_etd", label: "ETD Aktual", type: "date", section: "operational" },
      { key: "actual_eta", label: "ETA Aktual", type: "date", section: "operational" },
      { key: "tracking_info", label: "Info Tracking", type: "textarea", section: "operational" },
      { key: "op_notes", label: "Catatan Operasional", type: "textarea", section: "operational" },
    ],
  },

  // ── Customer-facing schemas ─────────────────────────────────────────────────
  customer_shipment: {
    label: "Permintaan Pengiriman", emoji: "📦",
    fields: [
      { key: "cargo_name", label: "Nama / Jenis Barang", type: "text", required: true, section: "quotation" },
      { key: "origin", label: "Kota / Negara Asal", type: "text", required: true, section: "quotation" },
      { key: "destination", label: "Kota / Negara Tujuan", type: "text", required: true, section: "quotation" },
      { key: "weight", label: "Berat Perkiraan (kg)", type: "number", section: "quotation" },
      { key: "volume", label: "Volume / Dimensi (m³ atau cm)", type: "text", section: "quotation" },
      { key: "qty", label: "Jumlah", type: "number", section: "quotation" },
      { key: "unit", label: "Satuan", type: "select", options: ["pcs", "kg", "ton", "box", "palet", "kontainer"], section: "quotation" },
      { key: "service_pref", label: "Layanan yang Diinginkan", type: "select", options: ["Sea Freight", "Air Freight", "Trucking", "Customs Clearance", "Door to Door", "Lainnya"], section: "quotation" },
      { key: "preferred_date", label: "Tanggal Pengiriman yang Diinginkan", type: "date", section: "quotation" },
      { key: "incoterms", label: "Incoterms (jika ada)", type: "select", options: ["EXW", "FOB", "CIF", "DAP", "DDP", "Tidak tahu"], section: "quotation" },
      { key: "special_req", label: "Persyaratan Khusus", type: "textarea", section: "quotation" },
      { key: "notes", label: "Catatan Tambahan", type: "textarea", section: "quotation" },
    ],
  },
  customer_quote: {
    label: "Permintaan Penawaran Harga", emoji: "💼",
    fields: [
      { key: "service_type", label: "Layanan yang Dibutuhkan", type: "select", required: true, options: ["Freight Forwarding", "Custom Clearance", "Trucking", "Warehousing", "Exim Consulting", "Full Logistics", "Lainnya"], section: "quotation" },
      { key: "cargo_desc", label: "Deskripsi Barang / Komoditi", type: "textarea", required: true, section: "quotation" },
      { key: "origin_country", label: "Negara / Kota Asal", type: "text", required: true, section: "quotation" },
      { key: "dest_country", label: "Negara / Kota Tujuan", type: "text", required: true, section: "quotation" },
      { key: "weight_volume", label: "Berat / Volume Perkiraan", type: "text", section: "quotation" },
      { key: "frequency", label: "Frekuensi Pengiriman", type: "select", options: ["Sekali", "Mingguan", "2x/bulan", "Bulanan", "Berkala (proyek)"], section: "quotation" },
      { key: "budget", label: "Budget Perkiraan", type: "text", section: "quotation" },
      { key: "timeline", label: "Target Tanggal Pengiriman Pertama", type: "date", section: "quotation" },
      { key: "notes", label: "Informasi Tambahan", type: "textarea", section: "quotation" },
    ],
  },
  customer_document: {
    label: "Pengiriman Dokumen", emoji: "📋",
    fields: [
      { key: "doc_type", label: "Jenis Dokumen", type: "select", required: true, options: ["Invoice", "Packing List", "Bill of Lading", "AWB", "COO", "MSDS", "Phytosanitary", "Fumigation", "Lainnya"], section: "quotation" },
      { key: "doc_reference", label: "Nomor Referensi / PO", type: "text", section: "quotation" },
      { key: "issued_by", label: "Diterbitkan Oleh", type: "text", section: "quotation" },
      { key: "issued_date", label: "Tanggal Terbit", type: "date", section: "quotation" },
      { key: "related_shipment", label: "Terkait Shipment / Order", type: "text", section: "quotation" },
      { key: "notes", label: "Keterangan", type: "textarea", section: "quotation" },
    ],
  },
  customer_complaint: {
    label: "Keluhan / Klaim", emoji: "⚠️",
    fields: [
      { key: "order_ref", label: "Nomor Order / Shipment", type: "text", required: true, section: "quotation" },
      { key: "complaint_type", label: "Jenis Keluhan", type: "select", required: true, options: ["Keterlambatan", "Kerusakan Barang", "Kehilangan Barang", "Dokumen Salah", "Overcharge", "Pelayanan", "Lainnya"], section: "quotation" },
      { key: "incident_date", label: "Tanggal Kejadian", type: "date", section: "quotation" },
      { key: "description", label: "Deskripsi Masalah", type: "textarea", required: true, section: "quotation" },
      { key: "claimed_amount", label: "Nilai Klaim (Rp)", type: "number", section: "quotation" },
      { key: "expected_resolution", label: "Penyelesaian yang Diharapkan", type: "textarea", section: "quotation" },
    ],
  },
  customer_product: {
    label: "Pemesanan Produk", emoji: "🛒",
    fields: [
      { key: "product_name", label: "Nama / Jenis Produk", type: "text", required: true, section: "quotation", placeholder: "Contoh: Green Bean Arabica Grade 1" },
      { key: "brand_spec", label: "Brand / Spesifikasi", type: "text", section: "quotation", placeholder: "Contoh: Grade A, moisture max 12%" },
      { key: "qty", label: "Jumlah yang Dipesan", type: "number", required: true, section: "quotation" },
      { key: "unit", label: "Satuan", type: "select", required: true, options: ["pcs", "kg", "ton", "box", "karton", "sak", "lusin", "unit", "lainnya"], section: "quotation" },
      { key: "target_price", label: "Target Harga (Rp)", type: "number", section: "quotation", placeholder: "Kosongkan jika tidak ada target" },
      { key: "currency", label: "Mata Uang", type: "select", options: ["IDR", "USD", "SGD", "EUR"], section: "quotation" },
      { key: "delivery_address", label: "Alamat Pengiriman", type: "textarea", required: true, section: "quotation" },
      { key: "preferred_delivery_date", label: "Tanggal Pengiriman yang Diinginkan", type: "date", section: "quotation" },
      { key: "payment_terms", label: "Cara Pembayaran", type: "select", options: ["Cash", "Transfer 50% DP", "Transfer Lunas", "Credit 30 hari", "Credit 45 hari", "Lainnya"], section: "quotation" },
      { key: "notes", label: "Catatan Tambahan", type: "textarea", section: "quotation", placeholder: "Persyaratan khusus, kemasan, dokumen, dll." },
    ],
  },

  // ── Admin / Internal schemas ────────────────────────────────────────────────
  admin_checklist: {
    label: "Checklist Proses", emoji: "✅",
    fields: [
      { key: "process_name", label: "Nama Proses / Pekerjaan", type: "text", required: true, section: "quotation" },
      { key: "order_ref", label: "Nomor Order / Referensi", type: "text", section: "quotation" },
      { key: "responsible", label: "Penanggung Jawab", type: "text", required: true, section: "quotation" },
      { key: "check_date", label: "Tanggal Pengecekan", type: "date", section: "quotation" },
      { key: "item_1", label: "Checklist Item 1", type: "select", options: ["✅ Selesai", "⏳ Proses", "❌ Belum"], section: "quotation" },
      { key: "item_2", label: "Checklist Item 2", type: "select", options: ["✅ Selesai", "⏳ Proses", "❌ Belum"], section: "quotation" },
      { key: "item_3", label: "Checklist Item 3", type: "select", options: ["✅ Selesai", "⏳ Proses", "❌ Belum"], section: "quotation" },
      { key: "overall_status", label: "Status Keseluruhan", type: "select", required: true, options: ["Completed", "In Progress", "Blocked", "Cancelled"], section: "quotation" },
      { key: "issues", label: "Kendala / Issues", type: "textarea", section: "quotation" },
      { key: "next_action", label: "Tindakan Selanjutnya", type: "textarea", section: "quotation" },
      { key: "notes", label: "Catatan", type: "textarea", section: "quotation" },
    ],
  },
  admin_handover: {
    label: "Serah Terima Pekerjaan", emoji: "🤝",
    fields: [
      { key: "job_ref", label: "Nomor Job / Order", type: "text", required: true, section: "quotation" },
      { key: "from_staff", label: "Diserahkan Oleh", type: "text", required: true, section: "quotation" },
      { key: "to_staff", label: "Diterima Oleh", type: "text", required: true, section: "quotation" },
      { key: "handover_date", label: "Tanggal Serah Terima", type: "date", required: true, section: "quotation" },
      { key: "job_description", label: "Deskripsi Pekerjaan", type: "textarea", required: true, section: "quotation" },
      { key: "current_status", label: "Status Saat Ini", type: "select", required: true, options: ["Baru Mulai", "Sedang Berjalan", "Menunggu Dokumen", "Menunggu Vendor", "Menunggu Customer", "Hampir Selesai"], section: "quotation" },
      { key: "pending_items", label: "Item yang Belum Selesai", type: "textarea", section: "quotation" },
      { key: "important_contacts", label: "Kontak Penting", type: "textarea", section: "quotation" },
      { key: "notes", label: "Catatan Tambahan", type: "textarea", section: "quotation" },
    ],
  },
  admin_inspection: {
    label: "Laporan Inspeksi", emoji: "🔍",
    fields: [
      { key: "inspection_ref", label: "Nomor Inspeksi / Referensi", type: "text", required: true, section: "quotation" },
      { key: "location", label: "Lokasi Inspeksi", type: "text", required: true, section: "quotation" },
      { key: "inspection_date", label: "Tanggal Inspeksi", type: "date", required: true, section: "quotation" },
      { key: "inspector", label: "Nama Inspektor", type: "text", required: true, section: "quotation" },
      { key: "goods_desc", label: "Deskripsi Barang / Aset", type: "textarea", required: true, section: "quotation" },
      { key: "qty_checked", label: "Jumlah Diperiksa", type: "number", section: "quotation" },
      { key: "qty_ok", label: "Jumlah OK", type: "number", section: "quotation" },
      { key: "qty_rejected", label: "Jumlah Ditolak / Rusak", type: "number", section: "quotation" },
      { key: "condition", label: "Kondisi Umum", type: "select", required: true, options: ["Baik", "Cukup Baik", "Ada Kerusakan Minor", "Kerusakan Signifikan", "Ditolak"], section: "quotation" },
      { key: "findings", label: "Temuan / Catatan", type: "textarea", section: "quotation" },
      { key: "recommendation", label: "Rekomendasi", type: "textarea", section: "quotation" },
    ],
  },
  admin_rfq_forward: {
    label: "Forward RFQ Customer ke Vendor", emoji: "📨",
    fields: [
      { key: "customer_name", label: "Nama Customer / Perusahaan", type: "text", required: true, section: "quotation", placeholder: "Contoh: PT Maju Bersama" },
      { key: "rfq_ref", label: "Nomor RFQ / Referensi Internal", type: "text", section: "quotation", placeholder: "Contoh: RFQ/2025/001" },
      { key: "service_needed", label: "Layanan yang Dibutuhkan", type: "select", required: true, options: ["Sea Freight", "Air Freight", "Trucking", "Customs Clearance", "Warehousing", "Exim Full Service", "Door to Door", "Lainnya"], section: "quotation" },
      { key: "cargo_desc", label: "Deskripsi Barang / Komoditi", type: "textarea", required: true, section: "quotation", placeholder: "Jenis barang, HS code, kondisi khusus, dll." },
      { key: "origin", label: "Asal (Kota / Negara)", type: "text", required: true, section: "quotation" },
      { key: "destination", label: "Tujuan (Kota / Negara)", type: "text", required: true, section: "quotation" },
      { key: "weight_volume", label: "Berat / Volume", type: "text", section: "quotation", placeholder: "Contoh: 500 kg / 2 CBM" },
      { key: "incoterms", label: "Incoterms", type: "select", options: ["EXW", "FOB", "CIF", "DAP", "DDP", "FCA", "Tidak ditentukan"], section: "quotation" },
      { key: "target_delivery_date", label: "Target Tanggal Pengiriman", type: "date", section: "quotation" },
      { key: "customer_budget", label: "Budget Customer (Rp / USD)", type: "text", section: "quotation", placeholder: "Kosongkan jika tidak diketahui" },
      { key: "special_req", label: "Persyaratan Khusus dari Customer", type: "textarea", section: "quotation", placeholder: "Contoh: butuh insurance, dokumen tertentu, dll." },
      { key: "quote_deadline", label: "Batas Waktu Penawaran dari Vendor", type: "date", required: true, section: "quotation" },
      { key: "vendor_phone", label: "No. WhatsApp Vendor (untuk notifikasi otomatis)", type: "text", section: "quotation", placeholder: "Contoh: 628123456789" },
      { key: "notes_to_vendor", label: "Pesan / Instruksi ke Vendor", type: "textarea", section: "quotation", placeholder: "Tambahan informasi yang perlu diketahui vendor" },
    ],
  },
  // ── Phase 2A: Product-First — Vendor Produk ─────────────────────────────
  product_vendor: {
    label: "Vendor Produk", emoji: "🏭",
    fields: [
      { key: "product_price", label: "Harga Produk (Rp)", type: "number", required: true, section: "quotation" },
      { key: "stock_status", label: "Status Stok", type: "select", required: true, options: ["Ready Stock", "Indent", "Pre-order", "Habis"], section: "quotation" },
      { key: "available_qty", label: "Qty Tersedia", type: "number", required: true, section: "quotation" },
      { key: "ready_date", label: "Tanggal Siap (Produk Ready)", type: "date", required: true, section: "quotation" },
      { key: "pickup_location", label: "Kota / Lokasi Pickup", type: "text", required: true, section: "quotation", placeholder: "Contoh: Cilincing, Jakarta Utara" },
      { key: "warehouse_address", label: "Alamat Lengkap Gudang", type: "textarea", required: true, section: "quotation", placeholder: "Alamat gudang / lokasi pengambilan produk" },
      { key: "product_documents", label: "Dokumen Produk", type: "text", section: "quotation", placeholder: "Link atau keterangan dokumen produk (COA, MSDS, dll.)", isUpload: true },
      { key: "notes", label: "Catatan Tambahan", type: "textarea", section: "both" },
      // Operational
      { key: "qty_confirmed", label: "Qty Dikonfirmasi", type: "number", required: true, section: "operational" },
      { key: "packing_status", label: "Status Packing", type: "select", options: ["Belum Packing", "Sedang Packing", "Sudah Packing"], section: "operational" },
      { key: "ready_confirmation", label: "Konfirmasi Kesiapan", type: "select", options: ["Siap Dijemput", "Butuh 1-2 Hari", "Butuh 3+ Hari"], section: "operational" },
      { key: "pickup_contact", label: "Kontak PIC Gudang", type: "text", section: "operational", placeholder: "Nama dan nomor WA PIC di lokasi" },
    ],
  },
};
