import type { StartupStageDefinition } from "./startupMigrationState.js";

type StageCategory = StartupStageDefinition["category"];
type RegistryRow = readonly [name: string, displayName: string, category: StageCategory];

// Keep this list explicit. Versions describe desired migration state, not the
// application build number; bump a stage only when its outcome changes.
const REGISTRY_ROWS: readonly RegistryRow[] = [
  ["pre_start_schema", "Pre-start schema migrations", "schema"],
  ["sessions", "Sessions migration", "schema"],
  ["companies", "Companies migration", "schema"],
  ["holding", "Holding migration", "schema"],
  ["portal", "Portal migration", "schema"],
  ["portal_payment_company_scope", "Portal payment company scope migration", "backfill"],
  ["accounting", "Accounting migration", "schema"],
  ["coa_governance", "COA governance migration", "schema"],
  ["coa_proposal", "COA proposal migration", "schema"],
  ["accounting_hub", "Accounting Hub migration", "schema"],
  ["ledger_guard", "Ledger Guard migration (P0 period-lock + immutability hardening)", "repair"],
  ["oauth_state", "OAuth state migration", "schema"],
  ["knowledge_base", "Knowledge base migration", "schema"],
  ["custom_roles", "Custom roles migration", "schema"],
  ["uom", "UOM migration", "schema"],
  ["freight_audit", "Freight audit log migration", "schema"],
  ["audit_fix", "Audit fix migration", "repair"],
  ["org_full", "Org full migration", "schema"],
  ["org_unique_codes", "Org unique codes migration", "schema"],
  ["org_role", "Org/role migration", "schema"],
  ["user_role_enum", "User role enum migration", "schema"],
  ["audit_log", "Audit log migration", "schema"],
  ["notification_log", "Notification log migration", "schema"],
  ["admin_notifications", "Admin notifications migration", "schema"],
  ["vendor_notifications", "Vendor notifications migration", "schema"],
  ["vendor_profile_fields", "Vendor profile fields migration", "schema"],
  ["supplier_enhancement", "Supplier enhancement migration (status/marketplace/documents/reviews)", "schema"],
  ["nav_preferences", "Nav preferences migration", "schema"],
  ["vendor_mini_form", "Vendor mini form migration", "schema"],
  ["customer_invoice_company_scope", "Customer invoice company scope migration", "backfill"],
  ["product_first_flow", "Product-first flow migration", "schema"],
  ["customer_quote_flow", "Customer quote flow migration", "schema"],
  ["enterprise", "Enterprise migration", "schema"],
  ["short_links", "Short links migration", "schema"],
  ["geofence", "Geofence migration", "schema"],
  ["order_fulfillment", "Order fulfillment migration", "schema"],
  ["trusted_devices", "Trusted devices migration", "schema"],
  ["erp_audit_reports", "ERP audit reports migration", "schema"],
  ["wa_template", "WA template migration", "schema"],
  ["rls", "RLS migration", "schema"],
  ["commodity_template", "Commodity template migration", "schema"],
  ["phase_1", "Phase 1 migration", "schema"],
  ["phase_2", "Phase 2 migration", "schema"],
  ["phase_3a_rfq_vendor_links", "Phase 3A RFQ vendor links FK fix", "repair"],
  ["unified_orders_quotes_views", "Unified orders/quotes views migration (Phase 3B)", "schema"],
  ["order_links", "Order links cross-reference migration (Phase 3C)", "schema"],
  ["push_subscriptions", "Push subscriptions migration", "schema"],
  ["pg_trgm", "pg_trgm indexes migration", "schema"],
  ["intelligence_alert_settings", "Intelligence alert settings migration", "schema"],
  ["ai_governance", "AI governance migration", "schema"],
  ["purchase_template", "Purchase template migration", "schema"],
  ["enterprise_workflow_template", "Enterprise workflow template migration", "schema"],
  ["order_progress", "Order progress migration", "schema"],
  ["exception_enum", "Exception enum migration", "schema"],
  ["order_exceptions", "Order exceptions migration", "schema"],
  ["step_4_template_snapshot", "Step 4 template snapshot migration", "schema"],
  ["service_template", "Service template migration", "schema"],
  ["paylabs_config", "Paylabs config migration", "schema"],
  ["paylabs_payment_methods", "Paylabs payment methods migration", "schema"],
  ["cost_center", "Cost Center migration", "schema"],
  ["sport_center", "Sport Center migration", "schema"],
  ["sport_center_payment_mirror_refresh", "Sport Center payment mirror trigger refresh", "repair"],
  ["sport_center_account_correction", "Sport Center account correction", "repair"],
  ["sport_center_company_invoice", "Sport Center company invoice migration", "schema"],
  ["sport_expenses", "Sport Expenses migration", "schema"],
  ["tenant", "Tenant migration", "schema"],
  ["driver_pod", "Driver POD migration", "schema"],
  ["driver_assignment", "Driver assignment migration", "schema"],
  ["vendor_company_assignments", "Vendor company assignments migration", "schema"],
  ["vendor_catalog_schema", "Vendor catalog schema migration", "schema"],
  ["vendor_profile_hardening", "Vendor profile hardening migration (Phase Final)", "repair"],
  ["featured_product", "Featured product migration", "schema"],
  ["marketplace_vendor_invoice", "Marketplace vendor invoice migration", "schema"],
  ["marketplace_ap_preparation", "Marketplace AP preparation migration", "schema"],
  ["logistic_vendor_fulfillments", "Logistic vendor fulfillments migration", "schema"],
  ["product_media", "Product media migration", "schema"],
  ["tax_rules", "Tax rules migration", "schema"],
  ["tax_spt", "Tax SPT migration", "schema"],
  ["tax_audit", "Tax audit migration (Fase 1)", "schema"],
  ["tax_coretax", "Tax Coretax C7 migration (Fase 4)", "schema"],
  ["freight_accounting", "Freight accounting migration", "schema"],
  ["logistics_rates", "Logistics rates migration", "schema"],
  ["bank_reconciliation_core", "Bank reconciliation core migration", "schema"],
  ["qris_settlement", "QRIS settlement migration", "schema"],
  ["usage_tracking", "Usage tracking migration", "schema"],
  ["bank_mutation_masters", "Bank mutation masters migration", "schema"],
  ["bank_mutation_import", "Bank mutation import migration", "schema"],
  ["freight_doc_verify", "Freight doc verify migration", "schema"],
  ["financial_period", "Financial period migration", "schema"],
  ["financial_closing", "Financial closing migration", "schema"],
  ["ledger_events_entry_id", "Ledger events entry_id migration", "schema"],
  ["sap_hardening", "SAP hardening migration", "repair"],
  ["finance_governance", "Finance governance migration", "schema"],
  ["bank_disbursement", "Bank disbursement migration", "schema"],
  ["expense_disbursement_bridge", "Expense-Disbursement bridge migration", "schema"],
  ["vendor_payments_historical", "Vendor payments migration (historical)", "backfill"],
  ["kas_bank", "Kas Bank migration", "schema"],
  ["cash_bank_enterprise", "Cash Bank enterprise migration", "schema"],
  ["finance_core", "Finance core migration", "schema"],
  ["bank_receipt", "Bank receipt migration", "schema"],
  ["advance_management", "Advance Management migration", "schema"],
  ["allocation_engine", "Allocation Engine migration", "schema"],
  ["treasury_batch_4", "Treasury Batch 4 migration", "schema"],
  ["bank_allocation_phase_2", "Bank Allocation Phase 2 migration", "schema"],
  ["expense_rule_engine", "Expense Rule Engine migration (Phase 3)", "schema"],
  ["expense_classification_columns", "Expense Classification columns migration (Phase 6D)", "schema"],
  ["logistics_payments", "ASK logistics_payments migration", "schema"],
  ["driver_module_load", "Driver migration module load", "runtime"],
  ["supabase_realtime", "Supabase realtime enable", "runtime"],
  ["accounting_defaults_seed", "Accounting defaults seed", "seed"],
  ["development_coa_sync", "Development COA sync", "reconciliation"],
  ["additional_tax_seed", "Additional tax seed", "seed"],
  ["expense_category_account_backfill", "Expense category account backfill", "backfill"],
  ["mdr_expense_category_backfill", "MDR expense category backfill", "backfill"],
  ["uom_seed", "UOM seed", "seed"],
  ["product_templates_seed", "Product templates seed", "seed"],
  ["logistics_catalog_demo_seed", "Logistics/catalog/demo seed chain", "seed"],
];

export const STARTUP_MIGRATION_REGISTRY: readonly StartupStageDefinition[] = REGISTRY_ROWS.map(
  ([name, _displayName, category]) => ({
    name,
    version: name === "portal_payment_company_scope" ? 3 : 1,
    critical: true,
    category,
  }),
);

const byDisplayName = new Map(REGISTRY_ROWS.map(([name, displayName]) => [displayName, name]));
const byName = new Map(STARTUP_MIGRATION_REGISTRY.map((stage) => [stage.name, stage]));

export function getStartupStageDefinition(displayName: string): StartupStageDefinition {
  const name = byDisplayName.get(displayName);
  if (!name) {
    throw new Error(`Startup stage is not registered: ${displayName}`);
  }
  return byName.get(name)!;
}