#!/usr/bin/env python3
"""Inject jasa translation keys into all 18 locale files."""
import os, re

BASE = "artifacts/customer-portal/src/i18n/locales"

TRANSLATIONS = {
  "id-ID": {
    "all": "Semua",
    "allServices": "Semua Layanan",
    "backBtn": "Kembali",
    "backToServices": "Kembali ke Layanan",
    "badgeDelivery": "On-Time Delivery",
    "badgeDeliveryMobile": "On-Time 98.5%",
    "badgeDeliverySub": "98.5% ketepatan waktu",
    "badgePPJK": "Berizin Resmi PPJK",
    "badgePPJKMobile": "Berizin PPJK",
    "badgePPJKSub": "Terdaftar Bea & Cukai",
    "badgeRating": "Rating 4.9 / 5.0",
    "badgeRatingMobile": "Rating 4.9/5.0",
    "badgeRatingSub": "Dari 1.200+ ulasan",
    "badgeTimeMobile": "Ketepatan waktu",
    "breadcrumbHome": "Beranda",
    "breadcrumbServices": "Layanan",
    "bulkConsultBtn": "Konsultasi Gratis",
    "bulkCtaFreeConsult": "Konsultasi gratis, tanpa komitmen.",
    "bulkCtaTeamWill": "Tim kami akan menyusun paket solusi yang tepat untuk kebutuhan logistik Anda.",
    "bulkDesc": "Solusi logistik kontrak end-to-end untuk kebutuhan ekspor, impor, dan distribusi skala besar.",
    "bulkFullForwardingDesc": "Penanganan penuh dari pengambilan kargo hingga pengiriman ke tujuan akhir.",
    "bulkSeaFreightBundleDesc": "Paket FCL/LCL dengan harga kontrak kompetitif dan jadwal tetap.",
    "bulkSubLabel": "Solusi Kontrak",
    "bulkSubmitBtn": "Ajukan Paket Borongan",
    "bulkTitle": "Paket Borongan",
    "bulkWarehouseDesc": "Layanan pergudangan, sortir, dan re-packing sesuai kebutuhan klien.",
    "bulkWarehouseTitle": "Warehousing & Handling",
    "categoryNotFound": "Kategori layanan tidak ditemukan.",
    "categoryServicesCount": "layanan",
    "categoryVendorCount": "penawaran vendor",
    "contactUsOffer": "Hubungi kami untuk mendapatkan penawaran.",
    "detail": "Lihat Detail",
    "filterAndSort": "Filter & Urutkan",
    "heroSubtitle": "Ekspor, impor, kepabeanan, dan pengiriman domestik — semua dalam satu platform terintegrasi.",
    "heroTitle1": "Solusi Logistik",
    "heroTitle2": "untuk Bisnis Anda",
    "heroTitleAccent": "Terpercaya",
    "modeBulk": "Paket Borongan",
    "modeBulkSub": "Solusi kontrak",
    "modeIndividual": "Item Mandiri",
    "modeIndividualSub": "Pilih per layanan",
    "mulairequest": "Mulai Request",
    "noResults": "Tidak ada hasil ditemukan.",
    "notFoundDesc": "Kategori yang Anda cari tidak tersedia. Silakan kembali ke halaman layanan.",
    "notFoundTitle": "Kategori Tidak Ditemukan",
    "noVendorOffers": "Belum ada penawaran vendor untuk layanan ini.",
    "pickService": "Pilih Layanan",
    "priceNego": "Harga dapat dinegosiasi",
    "registerAndRequest": "Daftar & Ajukan Request",
    "resetAllFilter": "Reset Semua Filter",
    "resetFilter": "Reset Filter",
    "searchPlaceholder": "Cari layanan, misal: air freight, trucking, pabean...",
    "searchResultCount": "layanan vendor ditemukan untuk",
    "searchResultsTitle": "Hasil Pencarian",
    "searchVendorPlaceholder": "Cari vendor...",
    "serviceType": "Tipe Layanan",
    "sortPrice": "Urutkan Harga",
    "statActiveClients": "Klien Aktif",
    "statDestinations": "Negara Tujuan",
    "statExperience": "Tahun Pengalaman",
    "tryChangeFilter": "Coba ubah filter atau kata kunci pencarian.",
    "vendorOffers": "Penawaran Vendor",
    "vendorOffersAvailable": "penawaran vendor tersedia",
    "vendorOffersDesc": "Vendor terdaftar yang menawarkan layanan ini.",
    "viewAll": "Lihat Semua",
  },
  "zh-CN": {
    "all": "全部",
    "allServices": "所有服务",
    "backBtn": "返回",
    "backToServices": "返回服务列表",
    "badgeDelivery": "准时交货",
    "badgeDeliveryMobile": "准时 98.5%",
    "badgeDeliverySub": "98.5% 准时率",
    "badgePPJK": "PPJK 持证企业",
    "badgePPJKMobile": "PPJK 持证",
    "badgePPJKSub": "已注册海关",
    "badgeRating": "评分 4.9 / 5.0",
    "badgeRatingMobile": "评分 4.9/5.0",
    "badgeRatingSub": "1,200+ 条评价",
    "badgeTimeMobile": "准时率",
    "breadcrumbHome": "首页",
    "breadcrumbServices": "服务",
    "bulkConsultBtn": "免费咨询",
    "bulkCtaFreeConsult": "免费咨询，无需承诺。",
    "bulkCtaTeamWill": "我们的团队将为您的物流需求制定最佳解决方案。",
    "bulkDesc": "为大规模出口、进口和配送提供端到端合同物流解决方案。",
    "bulkFullForwardingDesc": "从货物提取到目的地交付的全程处理。",
    "bulkSeaFreightBundleDesc": "具有竞争力的合同价格和固定班期的 FCL/LCL 套餐。",
    "bulkSubLabel": "合同解决方案",
    "bulkSubmitBtn": "申请批量套餐",
    "bulkTitle": "批量套餐",
    "bulkWarehouseDesc": "根据客户需求提供仓储、分拣和重新包装服务。",
    "bulkWarehouseTitle": "仓储与搬运",
    "categoryNotFound": "未找到该服务类别。",
    "categoryServicesCount": "项服务",
    "categoryVendorCount": "个供应商报价",
    "contactUsOffer": "请联系我们获取报价。",
    "detail": "查看详情",
    "filterAndSort": "筛选与排序",
    "heroSubtitle": "出口、进口、清关及国内配送——一站式整合平台。",
    "heroTitle1": "物流解决方案",
    "heroTitle2": "为您的业务",
    "heroTitleAccent": "值得信赖",
    "modeBulk": "批量套餐",
    "modeBulkSub": "合同解决方案",
    "modeIndividual": "单项服务",
    "modeIndividualSub": "按服务选择",
    "mulairequest": "开始申请",
    "noResults": "未找到任何结果。",
    "notFoundDesc": "您查找的类别不存在，请返回服务页面。",
    "notFoundTitle": "未找到类别",
    "noVendorOffers": "此服务暂无供应商报价。",
    "pickService": "选择服务",
    "priceNego": "价格可协商",
    "registerAndRequest": "注册并提交申请",
    "resetAllFilter": "重置所有筛选",
    "resetFilter": "重置筛选",
    "searchPlaceholder": "搜索服务，例如：空运、陆运、清关...",
    "searchResultCount": "个供应商服务匹配",
    "searchResultsTitle": "搜索结果",
    "searchVendorPlaceholder": "搜索供应商...",
    "serviceType": "服务类型",
    "sortPrice": "价格排序",
    "statActiveClients": "活跃客户",
    "statDestinations": "目的地国家",
    "statExperience": "年经验",
    "tryChangeFilter": "请尝试更改筛选条件或关键词。",
    "vendorOffers": "供应商报价",
    "vendorOffersAvailable": "个供应商报价可用",
    "vendorOffersDesc": "提供此服务的注册供应商。",
    "viewAll": "查看全部",
  },
  "en-US": {
    "all": "All",
    "allServices": "All Services",
    "backBtn": "Back",
    "backToServices": "Back to Services",
    "badgeDelivery": "On-Time Delivery",
    "badgeDeliveryMobile": "On-Time 98.5%",
    "badgeDeliverySub": "98.5% on-time rate",
    "badgePPJK": "PPJK Licensed",
    "badgePPJKMobile": "PPJK Licensed",
    "badgePPJKSub": "Registered with Customs",
    "badgeRating": "Rating 4.9 / 5.0",
    "badgeRatingMobile": "Rating 4.9/5.0",
    "badgeRatingSub": "From 1,200+ reviews",
    "badgeTimeMobile": "On-time rate",
    "breadcrumbHome": "Home",
    "breadcrumbServices": "Services",
    "bulkConsultBtn": "Free Consultation",
    "bulkCtaFreeConsult": "Free consultation, no commitment.",
    "bulkCtaTeamWill": "Our team will craft the right solution package for your logistics needs.",
    "bulkDesc": "End-to-end contract logistics for large-scale export, import, and distribution needs.",
    "bulkFullForwardingDesc": "Full handling from cargo pickup to delivery at final destination.",
    "bulkSeaFreightBundleDesc": "FCL/LCL packages with competitive contract rates and fixed schedules.",
    "bulkSubLabel": "Contract Solutions",
    "bulkSubmitBtn": "Submit Bulk Package",
    "bulkTitle": "Bulk Package",
    "bulkWarehouseDesc": "Warehousing, sorting, and re-packing services tailored to client needs.",
    "bulkWarehouseTitle": "Warehousing & Handling",
    "categoryNotFound": "Service category not found.",
    "categoryServicesCount": "services",
    "categoryVendorCount": "vendor offers",
    "contactUsOffer": "Contact us to get a quote.",
    "detail": "View Detail",
    "filterAndSort": "Filter & Sort",
    "heroSubtitle": "Export, import, customs clearance, and domestic delivery — all in one integrated platform.",
    "heroTitle1": "Logistics Solutions",
    "heroTitle2": "for Your Business",
    "heroTitleAccent": "Trusted",
    "modeBulk": "Bulk Package",
    "modeBulkSub": "Contract solutions",
    "modeIndividual": "Individual Items",
    "modeIndividualSub": "Choose per service",
    "mulairequest": "Start Request",
    "noResults": "No results found.",
    "notFoundDesc": "The category you are looking for is not available. Please return to the services page.",
    "notFoundTitle": "Category Not Found",
    "noVendorOffers": "No vendor offers available for this service yet.",
    "pickService": "Pick a Service",
    "priceNego": "Price negotiable",
    "registerAndRequest": "Register & Submit Request",
    "resetAllFilter": "Reset All Filters",
    "resetFilter": "Reset Filter",
    "searchPlaceholder": "Search services, e.g.: air freight, trucking, customs...",
    "searchResultCount": "vendor services found for",
    "searchResultsTitle": "Search Results",
    "searchVendorPlaceholder": "Search vendors...",
    "serviceType": "Service Type",
    "sortPrice": "Sort by Price",
    "statActiveClients": "Active Clients",
    "statDestinations": "Destination Countries",
    "statExperience": "Years of Experience",
    "tryChangeFilter": "Try changing the filter or search keyword.",
    "vendorOffers": "Vendor Offers",
    "vendorOffersAvailable": "vendor offers available",
    "vendorOffersDesc": "Registered vendors offering this service.",
    "viewAll": "View All",
  },
  "de-DE": {
    "all": "Alle",
    "allServices": "Alle Dienstleistungen",
    "backBtn": "Zurück",
    "backToServices": "Zurück zu den Diensten",
    "badgeDelivery": "Pünktliche Lieferung",
    "badgeDeliveryMobile": "Pünktlich 98,5 %",
    "badgeDeliverySub": "98,5 % Pünktlichkeitsrate",
    "badgePPJK": "PPJK-Lizenz",
    "badgePPJKMobile": "PPJK-Lizenz",
    "badgePPJKSub": "Beim Zoll registriert",
    "badgeRating": "Bewertung 4,9 / 5,0",
    "badgeRatingMobile": "Bewertung 4,9/5,0",
    "badgeRatingSub": "Aus 1.200+ Bewertungen",
    "badgeTimeMobile": "Pünktlichkeitsrate",
    "breadcrumbHome": "Startseite",
    "breadcrumbServices": "Dienste",
    "bulkConsultBtn": "Kostenlose Beratung",
    "bulkCtaFreeConsult": "Kostenlose Beratung, ohne Verpflichtung.",
    "bulkCtaTeamWill": "Unser Team entwickelt das passende Lösungspaket für Ihre Logistikbedürfnisse.",
    "bulkDesc": "End-to-End-Vertragslogistik für Groß-Export, -Import und -Distribution.",
    "bulkFullForwardingDesc": "Vollständige Abwicklung von der Frachtabholung bis zur Zustellung am Zielort.",
    "bulkSeaFreightBundleDesc": "FCL/LCL-Pakete mit wettbewerbsfähigen Vertragspreisen und festen Fahrplänen.",
    "bulkSubLabel": "Vertragslösungen",
    "bulkSubmitBtn": "Paketangebot einreichen",
    "bulkTitle": "Gesamtpaket",
    "bulkWarehouseDesc": "Lagerung, Sortierung und Neuverpackung nach Kundenbedarf.",
    "bulkWarehouseTitle": "Lagerhaltung & Umschlag",
    "categoryNotFound": "Dienstleistungskategorie nicht gefunden.",
    "categoryServicesCount": "Dienste",
    "categoryVendorCount": "Anbieterangebote",
    "contactUsOffer": "Kontaktieren Sie uns für ein Angebot.",
    "detail": "Details ansehen",
    "filterAndSort": "Filtern & Sortieren",
    "heroSubtitle": "Export, Import, Zollabfertigung und Inlandslieferung — alles auf einer integrierten Plattform.",
    "heroTitle1": "Logistiklösungen",
    "heroTitle2": "für Ihr Unternehmen",
    "heroTitleAccent": "Vertrauenswürdig",
    "modeBulk": "Gesamtpaket",
    "modeBulkSub": "Vertragslösungen",
    "modeIndividual": "Einzelne Artikel",
    "modeIndividualSub": "Pro Dienst wählen",
    "mulairequest": "Anfrage starten",
    "noResults": "Keine Ergebnisse gefunden.",
    "notFoundDesc": "Die gesuchte Kategorie ist nicht verfügbar. Bitte kehren Sie zur Dienstleistungsseite zurück.",
    "notFoundTitle": "Kategorie nicht gefunden",
    "noVendorOffers": "Noch keine Anbieterangebote für diesen Dienst.",
    "pickService": "Dienst auswählen",
    "priceNego": "Preis verhandelbar",
    "registerAndRequest": "Registrieren & Anfrage stellen",
    "resetAllFilter": "Alle Filter zurücksetzen",
    "resetFilter": "Filter zurücksetzen",
    "searchPlaceholder": "Dienste suchen, z. B.: Luftfracht, Transport, Zoll...",
    "searchResultCount": "Anbieterleistungen gefunden für",
    "searchResultsTitle": "Suchergebnisse",
    "searchVendorPlaceholder": "Anbieter suchen...",
    "serviceType": "Dienstleistungsart",
    "sortPrice": "Nach Preis sortieren",
    "statActiveClients": "Aktive Kunden",
    "statDestinations": "Zielländer",
    "statExperience": "Jahre Erfahrung",
    "tryChangeFilter": "Versuchen Sie, den Filter oder den Suchbegriff zu ändern.",
    "vendorOffers": "Anbieterangebote",
    "vendorOffersAvailable": "Anbieterangebote verfügbar",
    "vendorOffersDesc": "Registrierte Anbieter, die diesen Dienst anbieten.",
    "viewAll": "Alle ansehen",
  },
  "fr-FR": {
    "all": "Tous",
    "allServices": "Tous les services",
    "backBtn": "Retour",
    "backToServices": "Retour aux services",
    "badgeDelivery": "Livraison à l'heure",
    "badgeDeliveryMobile": "À l'heure 98,5 %",
    "badgeDeliverySub": "Taux de ponctualité 98,5 %",
    "badgePPJK": "Agréé PPJK",
    "badgePPJKMobile": "Agréé PPJK",
    "badgePPJKSub": "Enregistré aux Douanes",
    "badgeRating": "Note 4,9 / 5,0",
    "badgeRatingMobile": "Note 4,9/5,0",
    "badgeRatingSub": "Plus de 1 200 avis",
    "badgeTimeMobile": "Taux de ponctualité",
    "breadcrumbHome": "Accueil",
    "breadcrumbServices": "Services",
    "bulkConsultBtn": "Consultation gratuite",
    "bulkCtaFreeConsult": "Consultation gratuite, sans engagement.",
    "bulkCtaTeamWill": "Notre équipe élaborera le bon package de solutions pour vos besoins logistiques.",
    "bulkDesc": "Logistique contractuelle de bout en bout pour les besoins d'export, d'import et de distribution à grande échelle.",
    "bulkFullForwardingDesc": "Prise en charge complète de l'enlèvement jusqu'à la livraison à destination finale.",
    "bulkSeaFreightBundleDesc": "Packages FCL/LCL avec des tarifs contractuels compétitifs et des horaires fixes.",
    "bulkSubLabel": "Solutions contractuelles",
    "bulkSubmitBtn": "Soumettre un forfait groupé",
    "bulkTitle": "Forfait groupé",
    "bulkWarehouseDesc": "Services d'entreposage, de tri et de reconditionnement adaptés aux besoins des clients.",
    "bulkWarehouseTitle": "Entreposage & Manutention",
    "categoryNotFound": "Catégorie de service introuvable.",
    "categoryServicesCount": "services",
    "categoryVendorCount": "offres fournisseurs",
    "contactUsOffer": "Contactez-nous pour obtenir un devis.",
    "detail": "Voir le détail",
    "filterAndSort": "Filtrer et trier",
    "heroSubtitle": "Export, import, dédouanement et livraison nationale — tout sur une plateforme intégrée.",
    "heroTitle1": "Solutions logistiques",
    "heroTitle2": "pour votre entreprise",
    "heroTitleAccent": "De confiance",
    "modeBulk": "Forfait groupé",
    "modeBulkSub": "Solutions contractuelles",
    "modeIndividual": "Articles individuels",
    "modeIndividualSub": "Choisir par service",
    "mulairequest": "Démarrer une demande",
    "noResults": "Aucun résultat trouvé.",
    "notFoundDesc": "La catégorie que vous recherchez n'est pas disponible. Veuillez retourner à la page des services.",
    "notFoundTitle": "Catégorie introuvable",
    "noVendorOffers": "Pas encore d'offres de fournisseurs pour ce service.",
    "pickService": "Choisir un service",
    "priceNego": "Prix négociable",
    "registerAndRequest": "S'inscrire & soumettre une demande",
    "resetAllFilter": "Réinitialiser tous les filtres",
    "resetFilter": "Réinitialiser le filtre",
    "searchPlaceholder": "Rechercher des services, ex. : fret aérien, transport, douane...",
    "searchResultCount": "services fournisseurs trouvés pour",
    "searchResultsTitle": "Résultats de recherche",
    "searchVendorPlaceholder": "Rechercher des fournisseurs...",
    "serviceType": "Type de service",
    "sortPrice": "Trier par prix",
    "statActiveClients": "Clients actifs",
    "statDestinations": "Pays de destination",
    "statExperience": "Ans d'expérience",
    "tryChangeFilter": "Essayez de modifier le filtre ou le mot-clé de recherche.",
    "vendorOffers": "Offres des fournisseurs",
    "vendorOffersAvailable": "offres fournisseurs disponibles",
    "vendorOffersDesc": "Fournisseurs enregistrés proposant ce service.",
    "viewAll": "Voir tout",
  },
  "es-ES": {
    "all": "Todos",
    "allServices": "Todos los servicios",
    "backBtn": "Volver",
    "backToServices": "Volver a servicios",
    "badgeDelivery": "Entrega puntual",
    "badgeDeliveryMobile": "Puntual 98,5 %",
    "badgeDeliverySub": "Tasa de puntualidad 98,5 %",
    "badgePPJK": "Licencia PPJK",
    "badgePPJKMobile": "Licencia PPJK",
    "badgePPJKSub": "Registrado en Aduanas",
    "badgeRating": "Puntuación 4,9 / 5,0",
    "badgeRatingMobile": "Puntuación 4,9/5,0",
    "badgeRatingSub": "Más de 1.200 reseñas",
    "badgeTimeMobile": "Tasa de puntualidad",
    "breadcrumbHome": "Inicio",
    "breadcrumbServices": "Servicios",
    "bulkConsultBtn": "Consulta gratuita",
    "bulkCtaFreeConsult": "Consulta gratuita, sin compromiso.",
    "bulkCtaTeamWill": "Nuestro equipo diseñará el paquete de soluciones adecuado para sus necesidades logísticas.",
    "bulkDesc": "Logística contractual de extremo a extremo para necesidades de exportación, importación y distribución a gran escala.",
    "bulkFullForwardingDesc": "Gestión completa desde la recogida de la carga hasta la entrega en el destino final.",
    "bulkSeaFreightBundleDesc": "Paquetes FCL/LCL con tarifas contractuales competitivas y horarios fijos.",
    "bulkSubLabel": "Soluciones contractuales",
    "bulkSubmitBtn": "Enviar paquete global",
    "bulkTitle": "Paquete global",
    "bulkWarehouseDesc": "Servicios de almacenamiento, clasificación y reembalaje adaptados a las necesidades del cliente.",
    "bulkWarehouseTitle": "Almacenaje y manipulación",
    "categoryNotFound": "Categoría de servicio no encontrada.",
    "categoryServicesCount": "servicios",
    "categoryVendorCount": "ofertas de proveedor",
    "contactUsOffer": "Contáctenos para obtener una cotización.",
    "detail": "Ver detalle",
    "filterAndSort": "Filtrar y ordenar",
    "heroSubtitle": "Exportación, importación, despacho aduanero y entrega nacional — todo en una plataforma integrada.",
    "heroTitle1": "Soluciones logísticas",
    "heroTitle2": "para su negocio",
    "heroTitleAccent": "De confianza",
    "modeBulk": "Paquete global",
    "modeBulkSub": "Soluciones contractuales",
    "modeIndividual": "Artículos individuales",
    "modeIndividualSub": "Elegir por servicio",
    "mulairequest": "Iniciar solicitud",
    "noResults": "No se encontraron resultados.",
    "notFoundDesc": "La categoría que busca no está disponible. Vuelva a la página de servicios.",
    "notFoundTitle": "Categoría no encontrada",
    "noVendorOffers": "Aún no hay ofertas de proveedores para este servicio.",
    "pickService": "Seleccionar servicio",
    "priceNego": "Precio negociable",
    "registerAndRequest": "Registrarse y enviar solicitud",
    "resetAllFilter": "Restablecer todos los filtros",
    "resetFilter": "Restablecer filtro",
    "searchPlaceholder": "Buscar servicios, p. ej.: flete aéreo, transporte, aduanas...",
    "searchResultCount": "servicios de proveedor encontrados para",
    "searchResultsTitle": "Resultados de búsqueda",
    "searchVendorPlaceholder": "Buscar proveedores...",
    "serviceType": "Tipo de servicio",
    "sortPrice": "Ordenar por precio",
    "statActiveClients": "Clientes activos",
    "statDestinations": "Países de destino",
    "statExperience": "Años de experiencia",
    "tryChangeFilter": "Intente cambiar el filtro o la palabra clave de búsqueda.",
    "vendorOffers": "Ofertas de proveedores",
    "vendorOffersAvailable": "ofertas de proveedores disponibles",
    "vendorOffersDesc": "Proveedores registrados que ofrecen este servicio.",
    "viewAll": "Ver todo",
  },
  "ar-SA": {
    "all": "الكل",
    "allServices": "جميع الخدمات",
    "backBtn": "رجوع",
    "backToServices": "العودة إلى الخدمات",
    "badgeDelivery": "تسليم في الموعد",
    "badgeDeliveryMobile": "في الموعد 98.5%",
    "badgeDeliverySub": "معدل الالتزام بالمواعيد 98.5%",
    "badgePPJK": "مرخّص PPJK",
    "badgePPJKMobile": "مرخّص PPJK",
    "badgePPJKSub": "مسجّل في الجمارك",
    "badgeRating": "تقييم 4.9 / 5.0",
    "badgeRatingMobile": "تقييم 4.9/5.0",
    "badgeRatingSub": "من 1,200+ تقييم",
    "badgeTimeMobile": "معدل الالتزام",
    "breadcrumbHome": "الرئيسية",
    "breadcrumbServices": "الخدمات",
    "bulkConsultBtn": "استشارة مجانية",
    "bulkCtaFreeConsult": "استشارة مجانية، بلا التزام.",
    "bulkCtaTeamWill": "سيقوم فريقنا بصياغة حزمة الحلول المناسبة لاحتياجاتك اللوجستية.",
    "bulkDesc": "لوجستيات عقدية شاملة من البداية إلى النهاية لاحتياجات التصدير والاستيراد والتوزيع بالجملة.",
    "bulkFullForwardingDesc": "معالجة كاملة من استلام الشحنة حتى التسليم في الوجهة النهائية.",
    "bulkSeaFreightBundleDesc": "حزم FCL/LCL بأسعار تعاقدية تنافسية وجداول ثابتة.",
    "bulkSubLabel": "حلول تعاقدية",
    "bulkSubmitBtn": "تقديم حزمة جملة",
    "bulkTitle": "حزمة الجملة",
    "bulkWarehouseDesc": "خدمات التخزين والفرز وإعادة التغليف وفق احتياجات العميل.",
    "bulkWarehouseTitle": "التخزين والمناولة",
    "categoryNotFound": "فئة الخدمة غير موجودة.",
    "categoryServicesCount": "خدمات",
    "categoryVendorCount": "عروض موردين",
    "contactUsOffer": "تواصل معنا للحصول على عرض سعر.",
    "detail": "عرض التفاصيل",
    "filterAndSort": "تصفية وترتيب",
    "heroSubtitle": "تصدير، استيراد، تخليص جمركي، وتوصيل محلي — كل ذلك في منصة متكاملة واحدة.",
    "heroTitle1": "حلول لوجستية",
    "heroTitle2": "لأعمالك",
    "heroTitleAccent": "موثوقة",
    "modeBulk": "حزمة الجملة",
    "modeBulkSub": "حلول تعاقدية",
    "modeIndividual": "خدمات فردية",
    "modeIndividualSub": "اختر بالخدمة",
    "mulairequest": "بدء الطلب",
    "noResults": "لم يتم العثور على نتائج.",
    "notFoundDesc": "الفئة التي تبحث عنها غير متوفرة. يرجى العودة إلى صفحة الخدمات.",
    "notFoundTitle": "الفئة غير موجودة",
    "noVendorOffers": "لا توجد عروض موردين لهذه الخدمة بعد.",
    "pickService": "اختر خدمة",
    "priceNego": "السعر قابل للتفاوض",
    "registerAndRequest": "التسجيل وتقديم الطلب",
    "resetAllFilter": "إعادة تعيين جميع الفلاتر",
    "resetFilter": "إعادة تعيين الفلتر",
    "searchPlaceholder": "ابحث عن خدمات، مثل: شحن جوي، شحن بري، جمارك...",
    "searchResultCount": "خدمات مورد موجودة لـ",
    "searchResultsTitle": "نتائج البحث",
    "searchVendorPlaceholder": "ابحث عن موردين...",
    "serviceType": "نوع الخدمة",
    "sortPrice": "ترتيب حسب السعر",
    "statActiveClients": "عملاء نشطون",
    "statDestinations": "دول الوجهة",
    "statExperience": "سنوات خبرة",
    "tryChangeFilter": "حاول تغيير الفلتر أو كلمة البحث.",
    "vendorOffers": "عروض الموردين",
    "vendorOffersAvailable": "عروض موردين متاحة",
    "vendorOffersDesc": "الموردون المسجلون الذين يقدمون هذه الخدمة.",
    "viewAll": "عرض الكل",
  },
  "ar-AE": {
    "all": "الكل",
    "allServices": "جميع الخدمات",
    "backBtn": "رجوع",
    "backToServices": "العودة إلى الخدمات",
    "badgeDelivery": "تسليم في الموعد",
    "badgeDeliveryMobile": "في الموعد 98.5%",
    "badgeDeliverySub": "معدل الالتزام بالمواعيد 98.5%",
    "badgePPJK": "مرخّص PPJK",
    "badgePPJKMobile": "مرخّص PPJK",
    "badgePPJKSub": "مسجّل في الجمارك",
    "badgeRating": "تقييم 4.9 / 5.0",
    "badgeRatingMobile": "تقييم 4.9/5.0",
    "badgeRatingSub": "من 1,200+ تقييم",
    "badgeTimeMobile": "معدل الالتزام",
    "breadcrumbHome": "الرئيسية",
    "breadcrumbServices": "الخدمات",
    "bulkConsultBtn": "استشارة مجانية",
    "bulkCtaFreeConsult": "استشارة مجانية، بلا التزام.",
    "bulkCtaTeamWill": "سيقوم فريقنا بصياغة حزمة الحلول المناسبة لاحتياجاتك اللوجستية.",
    "bulkDesc": "لوجستيات عقدية شاملة من البداية إلى النهاية لاحتياجات التصدير والاستيراد والتوزيع بالجملة.",
    "bulkFullForwardingDesc": "معالجة كاملة من استلام الشحنة حتى التسليم في الوجهة النهائية.",
    "bulkSeaFreightBundleDesc": "حزم FCL/LCL بأسعار تعاقدية تنافسية وجداول ثابتة.",
    "bulkSubLabel": "حلول تعاقدية",
    "bulkSubmitBtn": "تقديم حزمة جملة",
    "bulkTitle": "حزمة الجملة",
    "bulkWarehouseDesc": "خدمات التخزين والفرز وإعادة التغليف وفق احتياجات العميل.",
    "bulkWarehouseTitle": "التخزين والمناولة",
    "categoryNotFound": "فئة الخدمة غير موجودة.",
    "categoryServicesCount": "خدمات",
    "categoryVendorCount": "عروض موردين",
    "contactUsOffer": "تواصل معنا للحصول على عرض سعر.",
    "detail": "عرض التفاصيل",
    "filterAndSort": "تصفية وترتيب",
    "heroSubtitle": "تصدير، استيراد، تخليص جمركي، وتوصيل محلي — كل ذلك في منصة متكاملة واحدة.",
    "heroTitle1": "حلول لوجستية",
    "heroTitle2": "لأعمالك",
    "heroTitleAccent": "موثوقة",
    "modeBulk": "حزمة الجملة",
    "modeBulkSub": "حلول تعاقدية",
    "modeIndividual": "خدمات فردية",
    "modeIndividualSub": "اختر بالخدمة",
    "mulairequest": "بدء الطلب",
    "noResults": "لم يتم العثور على نتائج.",
    "notFoundDesc": "الفئة التي تبحث عنها غير متوفرة. يرجى العودة إلى صفحة الخدمات.",
    "notFoundTitle": "الفئة غير موجودة",
    "noVendorOffers": "لا توجد عروض موردين لهذه الخدمة بعد.",
    "pickService": "اختر خدمة",
    "priceNego": "السعر قابل للتفاوض",
    "registerAndRequest": "التسجيل وتقديم الطلب",
    "resetAllFilter": "إعادة تعيين جميع الفلاتر",
    "resetFilter": "إعادة تعيين الفلتر",
    "searchPlaceholder": "ابحث عن خدمات، مثل: شحن جوي، شحن بري، جمارك...",
    "searchResultCount": "خدمات مورد موجودة لـ",
    "searchResultsTitle": "نتائج البحث",
    "searchVendorPlaceholder": "ابحث عن موردين...",
    "serviceType": "نوع الخدمة",
    "sortPrice": "ترتيب حسب السعر",
    "statActiveClients": "عملاء نشطون",
    "statDestinations": "دول الوجهة",
    "statExperience": "سنوات خبرة",
    "tryChangeFilter": "حاول تغيير الفلتر أو كلمة البحث.",
    "vendorOffers": "عروض الموردين",
    "vendorOffersAvailable": "عروض موردين متاحة",
    "vendorOffersDesc": "الموردون المسجلون الذين يقدمون هذه الخدمة.",
    "viewAll": "عرض الكل",
  },
  "en-GB": {
    "all": "All",
    "allServices": "All Services",
    "backBtn": "Back",
    "backToServices": "Back to Services",
    "badgeDelivery": "On-Time Delivery",
    "badgeDeliveryMobile": "On-Time 98.5%",
    "badgeDeliverySub": "98.5% on-time rate",
    "badgePPJK": "PPJK Licensed",
    "badgePPJKMobile": "PPJK Licensed",
    "badgePPJKSub": "Registered with Customs",
    "badgeRating": "Rating 4.9 / 5.0",
    "badgeRatingMobile": "Rating 4.9/5.0",
    "badgeRatingSub": "From 1,200+ reviews",
    "badgeTimeMobile": "On-time rate",
    "breadcrumbHome": "Home",
    "breadcrumbServices": "Services",
    "bulkConsultBtn": "Free Consultation",
    "bulkCtaFreeConsult": "Free consultation, no commitment.",
    "bulkCtaTeamWill": "Our team will craft the right solution package for your logistics needs.",
    "bulkDesc": "End-to-end contract logistics for large-scale export, import, and distribution needs.",
    "bulkFullForwardingDesc": "Full handling from cargo collection to delivery at final destination.",
    "bulkSeaFreightBundleDesc": "FCL/LCL packages with competitive contract rates and fixed schedules.",
    "bulkSubLabel": "Contract Solutions",
    "bulkSubmitBtn": "Submit Bulk Package",
    "bulkTitle": "Bulk Package",
    "bulkWarehouseDesc": "Warehousing, sorting, and re-packing services tailored to client needs.",
    "bulkWarehouseTitle": "Warehousing & Handling",
    "categoryNotFound": "Service category not found.",
    "categoryServicesCount": "services",
    "categoryVendorCount": "vendor offers",
    "contactUsOffer": "Contact us to get a quote.",
    "detail": "View Detail",
    "filterAndSort": "Filter & Sort",
    "heroSubtitle": "Export, import, customs clearance, and domestic delivery — all on one integrated platform.",
    "heroTitle1": "Logistics Solutions",
    "heroTitle2": "for Your Business",
    "heroTitleAccent": "Trusted",
    "modeBulk": "Bulk Package",
    "modeBulkSub": "Contract solutions",
    "modeIndividual": "Individual Items",
    "modeIndividualSub": "Choose per service",
    "mulairequest": "Start Request",
    "noResults": "No results found.",
    "notFoundDesc": "The category you are looking for is not available. Please return to the services page.",
    "notFoundTitle": "Category Not Found",
    "noVendorOffers": "No vendor offers available for this service yet.",
    "pickService": "Pick a Service",
    "priceNego": "Price negotiable",
    "registerAndRequest": "Register & Submit Request",
    "resetAllFilter": "Reset All Filters",
    "resetFilter": "Reset Filter",
    "searchPlaceholder": "Search services, e.g.: air freight, haulage, customs...",
    "searchResultCount": "vendor services found for",
    "searchResultsTitle": "Search Results",
    "searchVendorPlaceholder": "Search vendors...",
    "serviceType": "Service Type",
    "sortPrice": "Sort by Price",
    "statActiveClients": "Active Clients",
    "statDestinations": "Destination Countries",
    "statExperience": "Years of Experience",
    "tryChangeFilter": "Try changing the filter or search keyword.",
    "vendorOffers": "Vendor Offers",
    "vendorOffersAvailable": "vendor offers available",
    "vendorOffersDesc": "Registered vendors offering this service.",
    "viewAll": "View All",
  },
  "en-AU": {
    "all": "All",
    "allServices": "All Services",
    "backBtn": "Back",
    "backToServices": "Back to Services",
    "badgeDelivery": "On-Time Delivery",
    "badgeDeliveryMobile": "On-Time 98.5%",
    "badgeDeliverySub": "98.5% on-time rate",
    "badgePPJK": "PPJK Licensed",
    "badgePPJKMobile": "PPJK Licensed",
    "badgePPJKSub": "Registered with Customs",
    "badgeRating": "Rating 4.9 / 5.0",
    "badgeRatingMobile": "Rating 4.9/5.0",
    "badgeRatingSub": "From 1,200+ reviews",
    "badgeTimeMobile": "On-time rate",
    "breadcrumbHome": "Home",
    "breadcrumbServices": "Services",
    "bulkConsultBtn": "Free Consultation",
    "bulkCtaFreeConsult": "Free consultation, no commitment.",
    "bulkCtaTeamWill": "Our team will craft the right solution package for your logistics needs.",
    "bulkDesc": "End-to-end contract logistics for large-scale export, import, and distribution needs.",
    "bulkFullForwardingDesc": "Full handling from cargo pickup to delivery at final destination.",
    "bulkSeaFreightBundleDesc": "FCL/LCL packages with competitive contract rates and fixed schedules.",
    "bulkSubLabel": "Contract Solutions",
    "bulkSubmitBtn": "Submit Bulk Package",
    "bulkTitle": "Bulk Package",
    "bulkWarehouseDesc": "Warehousing, sorting, and re-packing services tailored to client needs.",
    "bulkWarehouseTitle": "Warehousing & Handling",
    "categoryNotFound": "Service category not found.",
    "categoryServicesCount": "services",
    "categoryVendorCount": "vendor offers",
    "contactUsOffer": "Contact us to get a quote.",
    "detail": "View Detail",
    "filterAndSort": "Filter & Sort",
    "heroSubtitle": "Export, import, customs clearance, and domestic delivery — all on one integrated platform.",
    "heroTitle1": "Logistics Solutions",
    "heroTitle2": "for Your Business",
    "heroTitleAccent": "Trusted",
    "modeBulk": "Bulk Package",
    "modeBulkSub": "Contract solutions",
    "modeIndividual": "Individual Items",
    "modeIndividualSub": "Choose per service",
    "mulairequest": "Start Request",
    "noResults": "No results found.",
    "notFoundDesc": "The category you are looking for is not available. Please return to the services page.",
    "notFoundTitle": "Category Not Found",
    "noVendorOffers": "No vendor offers available for this service yet.",
    "pickService": "Pick a Service",
    "priceNego": "Price negotiable",
    "registerAndRequest": "Register & Submit Request",
    "resetAllFilter": "Reset All Filters",
    "resetFilter": "Reset Filter",
    "searchPlaceholder": "Search services, e.g.: air freight, trucking, customs...",
    "searchResultCount": "vendor services found for",
    "searchResultsTitle": "Search Results",
    "searchVendorPlaceholder": "Search vendors...",
    "serviceType": "Service Type",
    "sortPrice": "Sort by Price",
    "statActiveClients": "Active Clients",
    "statDestinations": "Destination Countries",
    "statExperience": "Years of Experience",
    "tryChangeFilter": "Try changing the filter or search keyword.",
    "vendorOffers": "Vendor Offers",
    "vendorOffersAvailable": "vendor offers available",
    "vendorOffersDesc": "Registered vendors offering this service.",
    "viewAll": "View All",
  },
  "en-SG": {
    "all": "All",
    "allServices": "All Services",
    "backBtn": "Back",
    "backToServices": "Back to Services",
    "badgeDelivery": "On-Time Delivery",
    "badgeDeliveryMobile": "On-Time 98.5%",
    "badgeDeliverySub": "98.5% on-time rate",
    "badgePPJK": "PPJK Licensed",
    "badgePPJKMobile": "PPJK Licensed",
    "badgePPJKSub": "Registered with Customs",
    "badgeRating": "Rating 4.9 / 5.0",
    "badgeRatingMobile": "Rating 4.9/5.0",
    "badgeRatingSub": "From 1,200+ reviews",
    "badgeTimeMobile": "On-time rate",
    "breadcrumbHome": "Home",
    "breadcrumbServices": "Services",
    "bulkConsultBtn": "Free Consultation",
    "bulkCtaFreeConsult": "Free consultation, no commitment.",
    "bulkCtaTeamWill": "Our team will craft the right solution package for your logistics needs.",
    "bulkDesc": "End-to-end contract logistics for large-scale export, import, and distribution needs.",
    "bulkFullForwardingDesc": "Full handling from cargo pickup to delivery at final destination.",
    "bulkSeaFreightBundleDesc": "FCL/LCL packages with competitive contract rates and fixed schedules.",
    "bulkSubLabel": "Contract Solutions",
    "bulkSubmitBtn": "Submit Bulk Package",
    "bulkTitle": "Bulk Package",
    "bulkWarehouseDesc": "Warehousing, sorting, and re-packing services tailored to client needs.",
    "bulkWarehouseTitle": "Warehousing & Handling",
    "categoryNotFound": "Service category not found.",
    "categoryServicesCount": "services",
    "categoryVendorCount": "vendor offers",
    "contactUsOffer": "Contact us to get a quote.",
    "detail": "View Detail",
    "filterAndSort": "Filter & Sort",
    "heroSubtitle": "Export, import, customs clearance, and domestic delivery — all on one integrated platform.",
    "heroTitle1": "Logistics Solutions",
    "heroTitle2": "for Your Business",
    "heroTitleAccent": "Trusted",
    "modeBulk": "Bulk Package",
    "modeBulkSub": "Contract solutions",
    "modeIndividual": "Individual Items",
    "modeIndividualSub": "Choose per service",
    "mulairequest": "Start Request",
    "noResults": "No results found.",
    "notFoundDesc": "The category you are looking for is not available. Please return to the services page.",
    "notFoundTitle": "Category Not Found",
    "noVendorOffers": "No vendor offers available for this service yet.",
    "pickService": "Pick a Service",
    "priceNego": "Price negotiable",
    "registerAndRequest": "Register & Submit Request",
    "resetAllFilter": "Reset All Filters",
    "resetFilter": "Reset Filter",
    "searchPlaceholder": "Search services, e.g.: air freight, trucking, customs...",
    "searchResultCount": "vendor services found for",
    "searchResultsTitle": "Search Results",
    "searchVendorPlaceholder": "Search vendors...",
    "serviceType": "Service Type",
    "sortPrice": "Sort by Price",
    "statActiveClients": "Active Clients",
    "statDestinations": "Destination Countries",
    "statExperience": "Years of Experience",
    "tryChangeFilter": "Try changing the filter or search keyword.",
    "vendorOffers": "Vendor Offers",
    "vendorOffersAvailable": "vendor offers available",
    "vendorOffersDesc": "Registered vendors offering this service.",
    "viewAll": "View All",
  },
  "hi-IN": {
    "all": "सभी",
    "allServices": "सभी सेवाएं",
    "backBtn": "वापस",
    "backToServices": "सेवाओं पर वापस जाएं",
    "badgeDelivery": "समय पर डिलीवरी",
    "badgeDeliveryMobile": "समय पर 98.5%",
    "badgeDeliverySub": "98.5% समयबद्धता दर",
    "badgePPJK": "PPJK लाइसेंस प्राप्त",
    "badgePPJKMobile": "PPJK लाइसेंस",
    "badgePPJKSub": "सीमा शुल्क में पंजीकृत",
    "badgeRating": "रेटिंग 4.9 / 5.0",
    "badgeRatingMobile": "रेटिंग 4.9/5.0",
    "badgeRatingSub": "1,200+ समीक्षाओं से",
    "badgeTimeMobile": "समयबद्धता दर",
    "breadcrumbHome": "होम",
    "breadcrumbServices": "सेवाएं",
    "bulkConsultBtn": "निःशुल्क परामर्श",
    "bulkCtaFreeConsult": "निःशुल्क परामर्श, बिना प्रतिबद्धता।",
    "bulkCtaTeamWill": "हमारी टीम आपकी लॉजिस्टिक्स आवश्यकताओं के लिए सही समाधान पैकेज तैयार करेगी।",
    "bulkDesc": "बड़े पैमाने पर निर्यात, आयात और वितरण की जरूरतों के लिए एंड-टू-एंड कॉन्ट्रैक्ट लॉजिस्टिक्स।",
    "bulkFullForwardingDesc": "कार्गो पिकअप से अंतिम गंतव्य तक डिलीवरी तक पूर्ण प्रबंधन।",
    "bulkSeaFreightBundleDesc": "प्रतिस्पर्धी अनुबंध दरों और निश्चित शेड्यूल के साथ FCL/LCL पैकेज।",
    "bulkSubLabel": "अनुबंध समाधान",
    "bulkSubmitBtn": "बल्क पैकेज सबमिट करें",
    "bulkTitle": "बल्क पैकेज",
    "bulkWarehouseDesc": "ग्राहक की जरूरतों के अनुसार वेयरहाउसिंग, छंटाई और री-पैकिंग सेवाएं।",
    "bulkWarehouseTitle": "वेयरहाउसिंग और हैंडलिंग",
    "categoryNotFound": "सेवा श्रेणी नहीं मिली।",
    "categoryServicesCount": "सेवाएं",
    "categoryVendorCount": "विक्रेता ऑफर",
    "contactUsOffer": "कोटेशन के लिए हमसे संपर्क करें।",
    "detail": "विवरण देखें",
    "filterAndSort": "फ़िल्टर और सॉर्ट",
    "heroSubtitle": "निर्यात, आयात, सीमा शुल्क निकासी और घरेलू डिलीवरी — सब एक एकीकृत प्लेटफॉर्म पर।",
    "heroTitle1": "लॉजिस्टिक्स समाधान",
    "heroTitle2": "आपके व्यवसाय के लिए",
    "heroTitleAccent": "विश्वसनीय",
    "modeBulk": "बल्क पैकेज",
    "modeBulkSub": "अनुबंध समाधान",
    "modeIndividual": "व्यक्तिगत आइटम",
    "modeIndividualSub": "सेवा के अनुसार चुनें",
    "mulairequest": "अनुरोध शुरू करें",
    "noResults": "कोई परिणाम नहीं मिला।",
    "notFoundDesc": "आप जो श्रेणी खोज रहे हैं वह उपलब्ध नहीं है। कृपया सेवाओं पृष्ठ पर वापस जाएं।",
    "notFoundTitle": "श्रेणी नहीं मिली",
    "noVendorOffers": "इस सेवा के लिए अभी तक कोई विक्रेता ऑफर उपलब्ध नहीं।",
    "pickService": "सेवा चुनें",
    "priceNego": "मूल्य परक्राम्य",
    "registerAndRequest": "पंजीकरण करें और अनुरोध सबमिट करें",
    "resetAllFilter": "सभी फ़िल्टर रीसेट करें",
    "resetFilter": "फ़िल्टर रीसेट करें",
    "searchPlaceholder": "सेवाएं खोजें, जैसे: एयर फ्रेट, ट्रकिंग, कस्टम्स...",
    "searchResultCount": "विक्रेता सेवाएं मिलीं",
    "searchResultsTitle": "खोज परिणाम",
    "searchVendorPlaceholder": "विक्रेता खोजें...",
    "serviceType": "सेवा प्रकार",
    "sortPrice": "मूल्य के अनुसार सॉर्ट करें",
    "statActiveClients": "सक्रिय ग्राहक",
    "statDestinations": "गंतव्य देश",
    "statExperience": "वर्षों का अनुभव",
    "tryChangeFilter": "फ़िल्टर या खोज कीवर्ड बदलने का प्रयास करें।",
    "vendorOffers": "विक्रेता ऑफर",
    "vendorOffersAvailable": "विक्रेता ऑफर उपलब्ध",
    "vendorOffersDesc": "इस सेवा की पेशकश करने वाले पंजीकृत विक्रेता।",
    "viewAll": "सभी देखें",
  },
  "it-IT": {
    "all": "Tutti",
    "allServices": "Tutti i servizi",
    "backBtn": "Indietro",
    "backToServices": "Torna ai servizi",
    "badgeDelivery": "Consegna puntuale",
    "badgeDeliveryMobile": "Puntuale 98,5%",
    "badgeDeliverySub": "Tasso di puntualità 98,5%",
    "badgePPJK": "Licenza PPJK",
    "badgePPJKMobile": "Licenza PPJK",
    "badgePPJKSub": "Registrato in Dogana",
    "badgeRating": "Valutazione 4,9 / 5,0",
    "badgeRatingMobile": "Valutazione 4,9/5,0",
    "badgeRatingSub": "Da 1.200+ recensioni",
    "badgeTimeMobile": "Tasso di puntualità",
    "breadcrumbHome": "Home",
    "breadcrumbServices": "Servizi",
    "bulkConsultBtn": "Consulenza gratuita",
    "bulkCtaFreeConsult": "Consulenza gratuita, senza impegno.",
    "bulkCtaTeamWill": "Il nostro team elaborerà il pacchetto di soluzioni giusto per le vostre esigenze logistiche.",
    "bulkDesc": "Logistica contrattuale end-to-end per esigenze di export, import e distribuzione su larga scala.",
    "bulkFullForwardingDesc": "Gestione completa dal ritiro della merce alla consegna nella destinazione finale.",
    "bulkSeaFreightBundleDesc": "Pacchetti FCL/LCL con tariffe contrattuali competitive e orari fissi.",
    "bulkSubLabel": "Soluzioni contrattuali",
    "bulkSubmitBtn": "Invia pacchetto collettivo",
    "bulkTitle": "Pacchetto collettivo",
    "bulkWarehouseDesc": "Servizi di magazzinaggio, smistamento e riconfezionamento su misura per le esigenze del cliente.",
    "bulkWarehouseTitle": "Magazzinaggio e movimentazione",
    "categoryNotFound": "Categoria di servizio non trovata.",
    "categoryServicesCount": "servizi",
    "categoryVendorCount": "offerte fornitore",
    "contactUsOffer": "Contattaci per ricevere un preventivo.",
    "detail": "Vedi dettaglio",
    "filterAndSort": "Filtra e ordina",
    "heroSubtitle": "Export, import, sdoganamento e consegna nazionale — tutto su un'unica piattaforma integrata.",
    "heroTitle1": "Soluzioni logistiche",
    "heroTitle2": "per la tua azienda",
    "heroTitleAccent": "Affidabili",
    "modeBulk": "Pacchetto collettivo",
    "modeBulkSub": "Soluzioni contrattuali",
    "modeIndividual": "Articoli singoli",
    "modeIndividualSub": "Scegli per servizio",
    "mulairequest": "Inizia richiesta",
    "noResults": "Nessun risultato trovato.",
    "notFoundDesc": "La categoria che stai cercando non è disponibile. Torna alla pagina dei servizi.",
    "notFoundTitle": "Categoria non trovata",
    "noVendorOffers": "Ancora nessuna offerta fornitore per questo servizio.",
    "pickService": "Scegli un servizio",
    "priceNego": "Prezzo trattabile",
    "registerAndRequest": "Registrati e invia richiesta",
    "resetAllFilter": "Reimposta tutti i filtri",
    "resetFilter": "Reimposta filtro",
    "searchPlaceholder": "Cerca servizi, es.: trasporto aereo, autotrasporto, dogana...",
    "searchResultCount": "servizi fornitore trovati per",
    "searchResultsTitle": "Risultati di ricerca",
    "searchVendorPlaceholder": "Cerca fornitori...",
    "serviceType": "Tipo di servizio",
    "sortPrice": "Ordina per prezzo",
    "statActiveClients": "Clienti attivi",
    "statDestinations": "Paesi di destinazione",
    "statExperience": "Anni di esperienza",
    "tryChangeFilter": "Prova a modificare il filtro o la parola chiave di ricerca.",
    "vendorOffers": "Offerte fornitore",
    "vendorOffersAvailable": "offerte fornitore disponibili",
    "vendorOffersDesc": "Fornitori registrati che offrono questo servizio.",
    "viewAll": "Vedi tutto",
  },
  "ja-JP": {
    "all": "すべて",
    "allServices": "すべてのサービス",
    "backBtn": "戻る",
    "backToServices": "サービス一覧に戻る",
    "badgeDelivery": "定時配送",
    "badgeDeliveryMobile": "定時 98.5%",
    "badgeDeliverySub": "定時率 98.5%",
    "badgePPJK": "PPJK 認可取得",
    "badgePPJKMobile": "PPJK 認可",
    "badgePPJKSub": "税関登録済み",
    "badgeRating": "評価 4.9 / 5.0",
    "badgeRatingMobile": "評価 4.9/5.0",
    "badgeRatingSub": "1,200 件以上のレビューより",
    "badgeTimeMobile": "定時率",
    "breadcrumbHome": "ホーム",
    "breadcrumbServices": "サービス",
    "bulkConsultBtn": "無料相談",
    "bulkCtaFreeConsult": "無料相談、コミットメント不要。",
    "bulkCtaTeamWill": "私たちのチームが物流ニーズに最適なソリューションパッケージを作成します。",
    "bulkDesc": "大規模な輸出・輸入・流通ニーズに対応したエンドツーエンドの契約物流。",
    "bulkFullForwardingDesc": "貨物の集荷から最終目的地への配送まで全面的に対応。",
    "bulkSeaFreightBundleDesc": "競争力のある契約レートと固定スケジュールの FCL/LCL パッケージ。",
    "bulkSubLabel": "契約ソリューション",
    "bulkSubmitBtn": "一括パッケージを申請",
    "bulkTitle": "一括パッケージ",
    "bulkWarehouseDesc": "顧客ニーズに合わせた倉庫保管、仕分け、再梱包サービス。",
    "bulkWarehouseTitle": "倉庫保管・取り扱い",
    "categoryNotFound": "サービスカテゴリが見つかりません。",
    "categoryServicesCount": "件のサービス",
    "categoryVendorCount": "件のベンダー提案",
    "contactUsOffer": "お見積もりはお問い合わせください。",
    "detail": "詳細を見る",
    "filterAndSort": "絞り込みと並べ替え",
    "heroSubtitle": "輸出・輸入・通関・国内配送——すべてを一つの統合プラットフォームで。",
    "heroTitle1": "物流ソリューション",
    "heroTitle2": "お客様のビジネスのために",
    "heroTitleAccent": "信頼できる",
    "modeBulk": "一括パッケージ",
    "modeBulkSub": "契約ソリューション",
    "modeIndividual": "個別アイテム",
    "modeIndividualSub": "サービスごとに選択",
    "mulairequest": "リクエストを開始",
    "noResults": "結果が見つかりません。",
    "notFoundDesc": "お探しのカテゴリはありません。サービスページに戻ってください。",
    "notFoundTitle": "カテゴリが見つかりません",
    "noVendorOffers": "このサービスのベンダー提案はまだありません。",
    "pickService": "サービスを選択",
    "priceNego": "価格交渉可能",
    "registerAndRequest": "登録してリクエストを送信",
    "resetAllFilter": "すべてのフィルターをリセット",
    "resetFilter": "フィルターをリセット",
    "searchPlaceholder": "サービスを検索、例：航空貨物、トラック輸送、通関...",
    "searchResultCount": "件のベンダーサービスが見つかりました",
    "searchResultsTitle": "検索結果",
    "searchVendorPlaceholder": "ベンダーを検索...",
    "serviceType": "サービスタイプ",
    "sortPrice": "価格順に並べ替え",
    "statActiveClients": "アクティブクライアント",
    "statDestinations": "目的地の国",
    "statExperience": "年の経験",
    "tryChangeFilter": "フィルターや検索キーワードを変更してみてください。",
    "vendorOffers": "ベンダー提案",
    "vendorOffersAvailable": "件のベンダー提案が利用可能",
    "vendorOffersDesc": "このサービスを提供する登録済みベンダー。",
    "viewAll": "すべて見る",
  },
  "ko-KR": {
    "all": "전체",
    "allServices": "전체 서비스",
    "backBtn": "뒤로",
    "backToServices": "서비스 목록으로 돌아가기",
    "badgeDelivery": "정시 배송",
    "badgeDeliveryMobile": "정시 98.5%",
    "badgeDeliverySub": "정시율 98.5%",
    "badgePPJK": "PPJK 인가",
    "badgePPJKMobile": "PPJK 인가",
    "badgePPJKSub": "세관 등록 완료",
    "badgeRating": "평점 4.9 / 5.0",
    "badgeRatingMobile": "평점 4.9/5.0",
    "badgeRatingSub": "1,200개 이상의 리뷰",
    "badgeTimeMobile": "정시율",
    "breadcrumbHome": "홈",
    "breadcrumbServices": "서비스",
    "bulkConsultBtn": "무료 상담",
    "bulkCtaFreeConsult": "무료 상담, 약정 없음.",
    "bulkCtaTeamWill": "저희 팀이 귀사의 물류 요구에 맞는 솔루션 패키지를 제안합니다.",
    "bulkDesc": "대규모 수출, 수입 및 유통 요구를 위한 엔드투엔드 계약 물류.",
    "bulkFullForwardingDesc": "화물 픽업부터 최종 목적지 배송까지 전체 처리.",
    "bulkSeaFreightBundleDesc": "경쟁력 있는 계약 요금과 고정 스케줄의 FCL/LCL 패키지.",
    "bulkSubLabel": "계약 솔루션",
    "bulkSubmitBtn": "일괄 패키지 신청",
    "bulkTitle": "일괄 패키지",
    "bulkWarehouseDesc": "고객 요구에 맞춘 창고 보관, 분류 및 재포장 서비스.",
    "bulkWarehouseTitle": "창고 보관 및 취급",
    "categoryNotFound": "서비스 카테고리를 찾을 수 없습니다.",
    "categoryServicesCount": "개 서비스",
    "categoryVendorCount": "개 공급업체 제안",
    "contactUsOffer": "견적을 위해 문의해 주세요.",
    "detail": "상세 보기",
    "filterAndSort": "필터 및 정렬",
    "heroSubtitle": "수출, 수입, 통관 및 국내 배송 — 하나의 통합 플랫폼에서 모두.",
    "heroTitle1": "물류 솔루션",
    "heroTitle2": "귀사의 비즈니스를 위한",
    "heroTitleAccent": "신뢰할 수 있는",
    "modeBulk": "일괄 패키지",
    "modeBulkSub": "계약 솔루션",
    "modeIndividual": "개별 항목",
    "modeIndividualSub": "서비스별 선택",
    "mulairequest": "요청 시작",
    "noResults": "결과를 찾을 수 없습니다.",
    "notFoundDesc": "찾고 있는 카테고리가 없습니다. 서비스 페이지로 돌아가세요.",
    "notFoundTitle": "카테고리를 찾을 수 없음",
    "noVendorOffers": "이 서비스에 대한 공급업체 제안이 아직 없습니다.",
    "pickService": "서비스 선택",
    "priceNego": "가격 협상 가능",
    "registerAndRequest": "등록 및 요청 제출",
    "resetAllFilter": "모든 필터 초기화",
    "resetFilter": "필터 초기화",
    "searchPlaceholder": "서비스 검색, 예: 항공 화물, 트럭 운송, 통관...",
    "searchResultCount": "개 공급업체 서비스 검색됨",
    "searchResultsTitle": "검색 결과",
    "searchVendorPlaceholder": "공급업체 검색...",
    "serviceType": "서비스 유형",
    "sortPrice": "가격순 정렬",
    "statActiveClients": "활성 고객",
    "statDestinations": "목적지 국가",
    "statExperience": "년 경험",
    "tryChangeFilter": "필터나 검색 키워드를 변경해 보세요.",
    "vendorOffers": "공급업체 제안",
    "vendorOffersAvailable": "개 공급업체 제안 이용 가능",
    "vendorOffersDesc": "이 서비스를 제공하는 등록된 공급업체.",
    "viewAll": "전체 보기",
  },
  "ms-MY": {
    "all": "Semua",
    "allServices": "Semua Perkhidmatan",
    "backBtn": "Kembali",
    "backToServices": "Kembali ke Perkhidmatan",
    "badgeDelivery": "Penghantaran Tepat Masa",
    "badgeDeliveryMobile": "Tepat Masa 98.5%",
    "badgeDeliverySub": "Kadar ketepatan masa 98.5%",
    "badgePPJK": "Berlesen PPJK",
    "badgePPJKMobile": "Berlesen PPJK",
    "badgePPJKSub": "Berdaftar dengan Kastam",
    "badgeRating": "Penilaian 4.9 / 5.0",
    "badgeRatingMobile": "Penilaian 4.9/5.0",
    "badgeRatingSub": "Daripada 1,200+ ulasan",
    "badgeTimeMobile": "Kadar ketepatan masa",
    "breadcrumbHome": "Laman Utama",
    "breadcrumbServices": "Perkhidmatan",
    "bulkConsultBtn": "Perundingan Percuma",
    "bulkCtaFreeConsult": "Perundingan percuma, tanpa komitmen.",
    "bulkCtaTeamWill": "Pasukan kami akan menyediakan pakej penyelesaian yang tepat untuk keperluan logistik anda.",
    "bulkDesc": "Logistik kontrak hujung ke hujung untuk keperluan eksport, import dan pengagihan berskala besar.",
    "bulkFullForwardingDesc": "Pengendalian penuh dari pengambilan kargo hingga penghantaran ke destinasi akhir.",
    "bulkSeaFreightBundleDesc": "Pakej FCL/LCL dengan kadar kontrak kompetitif dan jadual tetap.",
    "bulkSubLabel": "Penyelesaian Kontrak",
    "bulkSubmitBtn": "Hantar Pakej Pukal",
    "bulkTitle": "Pakej Pukal",
    "bulkWarehouseDesc": "Perkhidmatan pergudangan, pengisihan dan pembungkusan semula mengikut keperluan pelanggan.",
    "bulkWarehouseTitle": "Pergudangan & Pengendalian",
    "categoryNotFound": "Kategori perkhidmatan tidak dijumpai.",
    "categoryServicesCount": "perkhidmatan",
    "categoryVendorCount": "tawaran vendor",
    "contactUsOffer": "Hubungi kami untuk mendapatkan sebut harga.",
    "detail": "Lihat Butiran",
    "filterAndSort": "Tapis & Susun",
    "heroSubtitle": "Eksport, import, pelepasan kastam dan penghantaran domestik — semuanya dalam satu platform bersepadu.",
    "heroTitle1": "Penyelesaian Logistik",
    "heroTitle2": "untuk Perniagaan Anda",
    "heroTitleAccent": "Dipercayai",
    "modeBulk": "Pakej Pukal",
    "modeBulkSub": "Penyelesaian kontrak",
    "modeIndividual": "Item Individu",
    "modeIndividualSub": "Pilih mengikut perkhidmatan",
    "mulairequest": "Mulakan Permintaan",
    "noResults": "Tiada hasil dijumpai.",
    "notFoundDesc": "Kategori yang anda cari tidak tersedia. Sila kembali ke halaman perkhidmatan.",
    "notFoundTitle": "Kategori Tidak Dijumpai",
    "noVendorOffers": "Tiada tawaran vendor untuk perkhidmatan ini buat masa ini.",
    "pickService": "Pilih Perkhidmatan",
    "priceNego": "Harga boleh dirunding",
    "registerAndRequest": "Daftar & Hantar Permintaan",
    "resetAllFilter": "Set Semula Semua Penapis",
    "resetFilter": "Set Semula Penapis",
    "searchPlaceholder": "Cari perkhidmatan, cth: pengangkutan udara, trak, kastam...",
    "searchResultCount": "perkhidmatan vendor dijumpai untuk",
    "searchResultsTitle": "Hasil Carian",
    "searchVendorPlaceholder": "Cari vendor...",
    "serviceType": "Jenis Perkhidmatan",
    "sortPrice": "Susun mengikut Harga",
    "statActiveClients": "Pelanggan Aktif",
    "statDestinations": "Negara Destinasi",
    "statExperience": "Tahun Pengalaman",
    "tryChangeFilter": "Cuba ubah penapis atau kata kunci carian.",
    "vendorOffers": "Tawaran Vendor",
    "vendorOffersAvailable": "tawaran vendor tersedia",
    "vendorOffersDesc": "Vendor berdaftar yang menawarkan perkhidmatan ini.",
    "viewAll": "Lihat Semua",
  },
  "nl-NL": {
    "all": "Alle",
    "allServices": "Alle diensten",
    "backBtn": "Terug",
    "backToServices": "Terug naar diensten",
    "badgeDelivery": "Op tijd geleverd",
    "badgeDeliveryMobile": "Op tijd 98,5%",
    "badgeDeliverySub": "Tijdigheidspercentage 98,5%",
    "badgePPJK": "PPJK-gecertificeerd",
    "badgePPJKMobile": "PPJK-gecertificeerd",
    "badgePPJKSub": "Geregistreerd bij Douane",
    "badgeRating": "Beoordeling 4,9 / 5,0",
    "badgeRatingMobile": "Beoordeling 4,9/5,0",
    "badgeRatingSub": "Uit 1.200+ beoordelingen",
    "badgeTimeMobile": "Tijdigheidspercentage",
    "breadcrumbHome": "Home",
    "breadcrumbServices": "Diensten",
    "bulkConsultBtn": "Gratis adviesgesprek",
    "bulkCtaFreeConsult": "Gratis adviesgesprek, zonder verplichtingen.",
    "bulkCtaTeamWill": "Ons team stelt het juiste oplossingspakket samen voor uw logistieke behoeften.",
    "bulkDesc": "End-to-end contractlogistiek voor grootschalige export-, import- en distributiebehoeften.",
    "bulkFullForwardingDesc": "Volledige afhandeling van vrachtverzameling tot levering op eindbestemming.",
    "bulkSeaFreightBundleDesc": "FCL/LCL-pakketten met concurrerende contracttarieven en vaste schema's.",
    "bulkSubLabel": "Contractoplossingen",
    "bulkSubmitBtn": "Bulkpakket indienen",
    "bulkTitle": "Bulkpakket",
    "bulkWarehouseDesc": "Opslag-, sorteer- en herverpakkingsdiensten op maat van de klant.",
    "bulkWarehouseTitle": "Opslag & Behandeling",
    "categoryNotFound": "Dienstcategorie niet gevonden.",
    "categoryServicesCount": "diensten",
    "categoryVendorCount": "leveranciersaanbiedingen",
    "contactUsOffer": "Neem contact met ons op voor een offerte.",
    "detail": "Details bekijken",
    "filterAndSort": "Filteren en sorteren",
    "heroSubtitle": "Export, import, douaneklaring en binnenlandse bezorging — alles op één geïntegreerd platform.",
    "heroTitle1": "Logistieke oplossingen",
    "heroTitle2": "voor uw bedrijf",
    "heroTitleAccent": "Betrouwbaar",
    "modeBulk": "Bulkpakket",
    "modeBulkSub": "Contractoplossingen",
    "modeIndividual": "Individuele items",
    "modeIndividualSub": "Per dienst kiezen",
    "mulairequest": "Aanvraag starten",
    "noResults": "Geen resultaten gevonden.",
    "notFoundDesc": "De gezochte categorie is niet beschikbaar. Ga terug naar de dienstenpagina.",
    "notFoundTitle": "Categorie niet gevonden",
    "noVendorOffers": "Nog geen leveranciersaanbiedingen voor deze dienst.",
    "pickService": "Kies een dienst",
    "priceNego": "Prijs onderhandelbaar",
    "registerAndRequest": "Registreren & aanvraag indienen",
    "resetAllFilter": "Alle filters opnieuw instellen",
    "resetFilter": "Filter opnieuw instellen",
    "searchPlaceholder": "Zoek diensten, bijv.: luchtvracht, vrachtvervoer, douane...",
    "searchResultCount": "leveranciersdiensten gevonden voor",
    "searchResultsTitle": "Zoekresultaten",
    "searchVendorPlaceholder": "Zoek leveranciers...",
    "serviceType": "Diensttype",
    "sortPrice": "Sorteren op prijs",
    "statActiveClients": "Actieve klanten",
    "statDestinations": "Bestemmingslanden",
    "statExperience": "Jaar ervaring",
    "tryChangeFilter": "Probeer het filter of het zoekwoord te wijzigen.",
    "vendorOffers": "Leveranciersaanbiedingen",
    "vendorOffersAvailable": "leveranciersaanbiedingen beschikbaar",
    "vendorOffersDesc": "Geregistreerde leveranciers die deze dienst aanbieden.",
    "viewAll": "Alles bekijken",
  },
  "zh-TW": {
    "all": "全部",
    "allServices": "所有服務",
    "backBtn": "返回",
    "backToServices": "返回服務列表",
    "badgeDelivery": "準時交貨",
    "badgeDeliveryMobile": "準時 98.5%",
    "badgeDeliverySub": "98.5% 準時率",
    "badgePPJK": "PPJK 持牌企業",
    "badgePPJKMobile": "PPJK 持牌",
    "badgePPJKSub": "已向海關登記",
    "badgeRating": "評分 4.9 / 5.0",
    "badgeRatingMobile": "評分 4.9/5.0",
    "badgeRatingSub": "1,200+ 則評價",
    "badgeTimeMobile": "準時率",
    "breadcrumbHome": "首頁",
    "breadcrumbServices": "服務",
    "bulkConsultBtn": "免費諮詢",
    "bulkCtaFreeConsult": "免費諮詢，無需承諾。",
    "bulkCtaTeamWill": "我們的團隊將為您的物流需求制定最佳解決方案。",
    "bulkDesc": "為大規模出口、進口和配送提供端到端合約物流解決方案。",
    "bulkFullForwardingDesc": "從貨物提取到目的地交付的全程處理。",
    "bulkSeaFreightBundleDesc": "具競爭力合約價格及固定班期的 FCL/LCL 套餐。",
    "bulkSubLabel": "合約解決方案",
    "bulkSubmitBtn": "申請批量套餐",
    "bulkTitle": "批量套餐",
    "bulkWarehouseDesc": "依客戶需求提供倉儲、分揀與重新包裝服務。",
    "bulkWarehouseTitle": "倉儲與搬運",
    "categoryNotFound": "未找到該服務類別。",
    "categoryServicesCount": "項服務",
    "categoryVendorCount": "個供應商報價",
    "contactUsOffer": "請聯絡我們以獲取報價。",
    "detail": "查看詳情",
    "filterAndSort": "篩選與排序",
    "heroSubtitle": "出口、進口、清關及國內配送——一站式整合平台。",
    "heroTitle1": "物流解決方案",
    "heroTitle2": "為您的業務",
    "heroTitleAccent": "值得信賴",
    "modeBulk": "批量套餐",
    "modeBulkSub": "合約解決方案",
    "modeIndividual": "單項服務",
    "modeIndividualSub": "按服務選擇",
    "mulairequest": "開始申請",
    "noResults": "未找到任何結果。",
    "notFoundDesc": "您查找的類別不存在，請返回服務頁面。",
    "notFoundTitle": "未找到類別",
    "noVendorOffers": "此服務暫無供應商報價。",
    "pickService": "選擇服務",
    "priceNego": "價格可協商",
    "registerAndRequest": "註冊並提交申請",
    "resetAllFilter": "重置所有篩選",
    "resetFilter": "重置篩選",
    "searchPlaceholder": "搜尋服務，例如：空運、陸運、清關...",
    "searchResultCount": "個供應商服務匹配",
    "searchResultsTitle": "搜尋結果",
    "searchVendorPlaceholder": "搜尋供應商...",
    "serviceType": "服務類型",
    "sortPrice": "價格排序",
    "statActiveClients": "活躍客戶",
    "statDestinations": "目的地國家",
    "statExperience": "年經驗",
    "tryChangeFilter": "請嘗試更改篩選條件或關鍵詞。",
    "vendorOffers": "供應商報價",
    "vendorOffersAvailable": "個供應商報價可用",
    "vendorOffersDesc": "提供此服務的注冊供應商。",
    "viewAll": "查看全部",
  },
}

# Key ordering: consistent across all locales
KEY_ORDER = [
  "all", "allServices", "backBtn", "backToServices",
  "badgeDelivery", "badgeDeliveryMobile", "badgeDeliverySub",
  "badgePPJK", "badgePPJKMobile", "badgePPJKSub",
  "badgeRating", "badgeRatingMobile", "badgeRatingSub", "badgeTimeMobile",
  "breadcrumbHome", "breadcrumbServices",
  "bulkConsultBtn", "bulkCtaFreeConsult", "bulkCtaTeamWill",
  "bulkDesc", "bulkFullForwardingDesc", "bulkSeaFreightBundleDesc",
  "bulkSubLabel", "bulkSubmitBtn", "bulkTitle",
  "bulkWarehouseDesc", "bulkWarehouseTitle",
  "categoryNotFound", "categoryServicesCount", "categoryVendorCount",
  "contactUsOffer", "detail", "filterAndSort",
  "heroSubtitle", "heroTitle1", "heroTitle2", "heroTitleAccent",
  "modeBulk", "modeBulkSub", "modeIndividual", "modeIndividualSub",
  "mulairequest", "noResults", "notFoundDesc", "notFoundTitle", "noVendorOffers",
  "pickService", "priceNego", "registerAndRequest",
  "resetAllFilter", "resetFilter",
  "searchPlaceholder", "searchResultCount", "searchResultsTitle", "searchVendorPlaceholder",
  "serviceType", "sortPrice",
  "statActiveClients", "statDestinations", "statExperience",
  "tryChangeFilter", "vendorOffers", "vendorOffersAvailable", "vendorOffersDesc", "viewAll",
]

def escape_ts(val):
    # Use single quotes; escape any single quotes inside
    return val.replace("'", "\\'")

def build_jasa_block(locale_id):
    t = TRANSLATIONS[locale_id]
    lines = ["  jasa: {"]
    for k in KEY_ORDER:
        v = t.get(k, "")
        lines.append(f"    {k}: '{escape_ts(v)}',")
    lines.append("  },")
    return "\n".join(lines)

errors = []
for locale_id, _ in TRANSLATIONS.items():
    fpath = os.path.join(BASE, f"{locale_id}.ts")
    if not os.path.exists(fpath):
        errors.append(f"MISSING: {fpath}")
        continue

    with open(fpath, "r", encoding="utf-8") as f:
        content = f.read()

    # Check not already injected
    if "jasa:" in content:
        print(f"SKIP {locale_id}: jasa already present")
        continue

    # Find insertion point: just before `export default locale;`
    anchor = "export default locale;"
    idx = content.rfind(anchor)
    if idx == -1:
        errors.append(f"NO_ANCHOR: {fpath}")
        continue

    # Trim trailing whitespace/newlines before anchor, then insert block + newline
    before = content[:idx].rstrip()
    after = content[idx:]

    jasa_block = build_jasa_block(locale_id)
    new_content = before + "\n\n" + jasa_block + "\n\n" + after

    with open(fpath, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"OK {locale_id}: {len(KEY_ORDER)} keys injected")

if errors:
    print("\nERRORS:")
    for e in errors:
        print(f"  {e}")
else:
    print("\nAll locales done, no errors.")
